// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.19.1
// source: ai.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "rustygod.ai";

export interface ProductHit {
  id: string;
  name: string;
  slug: string;
  currency: string;
  priceAmount: string;
  score: number;
}

/**
 * Lexical tier today (pg_trgm over Saleor's own gin indexes), vector tier
 * next (pgvector/Qdrant) — same RPC, stronger backend.
 */
export interface SearchProductsRequest {
  query: string;
  channel: string;
  first: number;
}

export interface SearchProductsResponse {
  results: ProductHit[];
}

/** Collaborative signal from Django's order_orderline co-occurrence. */
export interface RecommendProductsRequest {
  variantId: string;
  channel: string;
  first: number;
}

export interface RecommendProductsResponse {
  results: ProductHit[];
}

/**
 * Retrieval-grounded shopping assistant (deterministic v1; LLM backend
 * milestone plugs into the same stream).
 */
export interface ChatMessage {
  role: string;
  text: string;
}

export interface ChatRequest {
  message: string;
  channel: string;
  history: ChatMessage[];
}

export interface ChatChunk {
  text: string;
  products: ProductHit[];
  done: boolean;
}

function createBaseProductHit(): ProductHit {
  return { id: "", name: "", slug: "", currency: "", priceAmount: "", score: 0 };
}

export const ProductHit: MessageFns<ProductHit> = {
  encode(message: ProductHit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.slug !== "") {
      writer.uint32(26).string(message.slug);
    }
    if (message.currency !== "") {
      writer.uint32(34).string(message.currency);
    }
    if (message.priceAmount !== "") {
      writer.uint32(42).string(message.priceAmount);
    }
    if (message.score !== 0) {
      writer.uint32(49).double(message.score);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductHit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProductHit();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.slug = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.currency = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.priceAmount = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.score = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ProductHit>, I>>(base?: I): ProductHit {
    return ProductHit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductHit>, I>>(object: I): ProductHit {
    const message = createBaseProductHit();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.slug = object.slug ?? "";
    message.currency = object.currency ?? "";
    message.priceAmount = object.priceAmount ?? "";
    message.score = object.score ?? 0;
    return message;
  },
};

function createBaseSearchProductsRequest(): SearchProductsRequest {
  return { query: "", channel: "", first: 0 };
}

export const SearchProductsRequest: MessageFns<SearchProductsRequest> = {
  encode(message: SearchProductsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    if (message.first !== 0) {
      writer.uint32(24).int32(message.first);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchProductsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSearchProductsRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.query = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.channel = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.first = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SearchProductsRequest>, I>>(base?: I): SearchProductsRequest {
    return SearchProductsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchProductsRequest>, I>>(object: I): SearchProductsRequest {
    const message = createBaseSearchProductsRequest();
    message.query = object.query ?? "";
    message.channel = object.channel ?? "";
    message.first = object.first ?? 0;
    return message;
  },
};

function createBaseSearchProductsResponse(): SearchProductsResponse {
  return { results: [] };
}

export const SearchProductsResponse: MessageFns<SearchProductsResponse> = {
  encode(message: SearchProductsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      ProductHit.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchProductsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSearchProductsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.results.push(ProductHit.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SearchProductsResponse>, I>>(base?: I): SearchProductsResponse {
    return SearchProductsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchProductsResponse>, I>>(object: I): SearchProductsResponse {
    const message = createBaseSearchProductsResponse();
    message.results = object.results?.map((e) => ProductHit.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecommendProductsRequest(): RecommendProductsRequest {
  return { variantId: "", channel: "", first: 0 };
}

export const RecommendProductsRequest: MessageFns<RecommendProductsRequest> = {
  encode(message: RecommendProductsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variantId !== "") {
      writer.uint32(10).string(message.variantId);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    if (message.first !== 0) {
      writer.uint32(24).int32(message.first);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecommendProductsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRecommendProductsRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.variantId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.channel = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.first = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RecommendProductsRequest>, I>>(base?: I): RecommendProductsRequest {
    return RecommendProductsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecommendProductsRequest>, I>>(object: I): RecommendProductsRequest {
    const message = createBaseRecommendProductsRequest();
    message.variantId = object.variantId ?? "";
    message.channel = object.channel ?? "";
    message.first = object.first ?? 0;
    return message;
  },
};

function createBaseRecommendProductsResponse(): RecommendProductsResponse {
  return { results: [] };
}

export const RecommendProductsResponse: MessageFns<RecommendProductsResponse> = {
  encode(message: RecommendProductsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      ProductHit.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecommendProductsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRecommendProductsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.results.push(ProductHit.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RecommendProductsResponse>, I>>(base?: I): RecommendProductsResponse {
    return RecommendProductsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecommendProductsResponse>, I>>(object: I): RecommendProductsResponse {
    const message = createBaseRecommendProductsResponse();
    message.results = object.results?.map((e) => ProductHit.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChatMessage(): ChatMessage {
  return { role: "", text: "" };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.role !== "") {
      writer.uint32(10).string(message.role);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChatMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.role = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.text = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.role = object.role ?? "";
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseChatRequest(): ChatRequest {
  return { message: "", channel: "", history: [] };
}

export const ChatRequest: MessageFns<ChatRequest> = {
  encode(message: ChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    for (const v of message.history) {
      ChatMessage.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChatRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.message = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.channel = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.history.push(ChatMessage.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ChatRequest>, I>>(base?: I): ChatRequest {
    return ChatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatRequest>, I>>(object: I): ChatRequest {
    const message = createBaseChatRequest();
    message.message = object.message ?? "";
    message.channel = object.channel ?? "";
    message.history = object.history?.map((e) => ChatMessage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChatChunk(): ChatChunk {
  return { text: "", products: [], done: false };
}

export const ChatChunk: MessageFns<ChatChunk> = {
  encode(message: ChatChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    for (const v of message.products) {
      ProductHit.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.done !== false) {
      writer.uint32(24).bool(message.done);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChatChunk();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.text = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.products.push(ProductHit.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.done = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ChatChunk>, I>>(base?: I): ChatChunk {
    return ChatChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatChunk>, I>>(object: I): ChatChunk {
    const message = createBaseChatChunk();
    message.text = object.text ?? "";
    message.products = object.products?.map((e) => ProductHit.fromPartial(e)) || [];
    message.done = object.done ?? false;
    return message;
  },
};

export type SemanticSearchService = typeof SemanticSearchService;
export const SemanticSearchService = {
  searchProducts: {
    path: "/rustygod.ai.SemanticSearch/SearchProducts" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SearchProductsRequest): Buffer =>
      Buffer.from(SearchProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SearchProductsRequest => SearchProductsRequest.decode(value),
    responseSerialize: (value: SearchProductsResponse): Buffer =>
      Buffer.from(SearchProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SearchProductsResponse => SearchProductsResponse.decode(value),
  },
} as const;

export interface SemanticSearchServer extends UntypedServiceImplementation {
  searchProducts: handleUnaryCall<SearchProductsRequest, SearchProductsResponse>;
}

export interface SemanticSearchClient extends Client {
  searchProducts(
    request: SearchProductsRequest,
    callback: (error: ServiceError | null, response: SearchProductsResponse) => void,
  ): ClientUnaryCall;
  searchProducts(
    request: SearchProductsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SearchProductsResponse) => void,
  ): ClientUnaryCall;
  searchProducts(
    request: SearchProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SearchProductsResponse) => void,
  ): ClientUnaryCall;
}

export const SemanticSearchClient = makeGenericClientConstructor(
  SemanticSearchService,
  "rustygod.ai.SemanticSearch",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SemanticSearchClient;
  service: typeof SemanticSearchService;
  serviceName: string;
};

export type RecommenderService = typeof RecommenderService;
export const RecommenderService = {
  recommendProducts: {
    path: "/rustygod.ai.Recommender/RecommendProducts" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RecommendProductsRequest): Buffer =>
      Buffer.from(RecommendProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RecommendProductsRequest => RecommendProductsRequest.decode(value),
    responseSerialize: (value: RecommendProductsResponse): Buffer =>
      Buffer.from(RecommendProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RecommendProductsResponse => RecommendProductsResponse.decode(value),
  },
} as const;

export interface RecommenderServer extends UntypedServiceImplementation {
  recommendProducts: handleUnaryCall<RecommendProductsRequest, RecommendProductsResponse>;
}

export interface RecommenderClient extends Client {
  recommendProducts(
    request: RecommendProductsRequest,
    callback: (error: ServiceError | null, response: RecommendProductsResponse) => void,
  ): ClientUnaryCall;
  recommendProducts(
    request: RecommendProductsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RecommendProductsResponse) => void,
  ): ClientUnaryCall;
  recommendProducts(
    request: RecommendProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RecommendProductsResponse) => void,
  ): ClientUnaryCall;
}

export const RecommenderClient = makeGenericClientConstructor(
  RecommenderService,
  "rustygod.ai.Recommender",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RecommenderClient;
  service: typeof RecommenderService;
  serviceName: string;
};

export type ChatAgentService = typeof ChatAgentService;
export const ChatAgentService = {
  chat: {
    path: "/rustygod.ai.ChatAgent/Chat" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: ChatRequest): Buffer => Buffer.from(ChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatRequest => ChatRequest.decode(value),
    responseSerialize: (value: ChatChunk): Buffer => Buffer.from(ChatChunk.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatChunk => ChatChunk.decode(value),
  },
} as const;

export interface ChatAgentServer extends UntypedServiceImplementation {
  chat: handleServerStreamingCall<ChatRequest, ChatChunk>;
}

export interface ChatAgentClient extends Client {
  chat(request: ChatRequest, options?: Partial<CallOptions>): ClientReadableStream<ChatChunk>;
  chat(request: ChatRequest, metadata?: Metadata, options?: Partial<CallOptions>): ClientReadableStream<ChatChunk>;
}

export const ChatAgentClient = makeGenericClientConstructor(ChatAgentService, "rustygod.ai.ChatAgent") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ChatAgentClient;
  service: typeof ChatAgentService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
