// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.19.1
// source: auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Error } from "./common.js";

export const protobufPackage = "rustygod.auth";

/**
 * Django-compatible auth: PBKDF2/bcrypt verification (no password resets)
 * and RS256 JWTs from the same RSA_PRIVATE_KEY.
 */
export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  userId: string;
  isStaff: boolean;
  errors: Error[];
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  errors: Error[];
}

export interface VerifyTokenRequest {
  token: string;
}

export interface VerifyTokenResponse {
  valid: boolean;
  userId: string;
  email: string;
  tokenType: string;
  isStaff: boolean;
  errors: Error[];
}

export interface CheckPermissionRequest {
  userId: string;
  codename: string;
}

export interface CheckPermissionResponse {
  allowed: boolean;
}

export interface CreateAppTokenRequest {
  appId: number;
  name: string;
}

export interface CreateAppTokenResponse {
  tokenId: number;
  /** shown once — only the hash is stored */
  token: string;
  errors: Error[];
}

export interface VerifyAppTokenRequest {
  token: string;
}

export interface VerifyAppTokenResponse {
  valid: boolean;
  appId: number;
  appName: string;
}

export interface RevokeAppTokenRequest {
  tokenId: number;
}

export interface RevokeAppTokenResponse {
  revoked: boolean;
  errors: Error[];
}

function createBaseLoginRequest(): LoginRequest {
  return { email: "", password: "" };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.email = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.password = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return { accessToken: "", refreshToken: "", userId: "", isStaff: false, errors: [] };
}

export const LoginResponse: MessageFns<LoginResponse> = {
  encode(message: LoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.isStaff !== false) {
      writer.uint32(32).bool(message.isStaff);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.accessToken = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.refreshToken = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.userId = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.isStaff = reader.bool();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(base?: I): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(object: I): LoginResponse {
    const message = createBaseLoginResponse();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? "";
    message.userId = object.userId ?? "";
    message.isStaff = object.isStaff ?? false;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRefreshTokenRequest(): RefreshTokenRequest {
  return { refreshToken: "" };
}

export const RefreshTokenRequest: MessageFns<RefreshTokenRequest> = {
  encode(message: RefreshTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refreshToken !== "") {
      writer.uint32(10).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRefreshTokenRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.refreshToken = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(base?: I): RefreshTokenRequest {
    return RefreshTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(object: I): RefreshTokenRequest {
    const message = createBaseRefreshTokenRequest();
    message.refreshToken = object.refreshToken ?? "";
    return message;
  },
};

function createBaseRefreshTokenResponse(): RefreshTokenResponse {
  return { accessToken: "", errors: [] };
}

export const RefreshTokenResponse: MessageFns<RefreshTokenResponse> = {
  encode(message: RefreshTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRefreshTokenResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.accessToken = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RefreshTokenResponse>, I>>(base?: I): RefreshTokenResponse {
    return RefreshTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenResponse>, I>>(object: I): RefreshTokenResponse {
    const message = createBaseRefreshTokenResponse();
    message.accessToken = object.accessToken ?? "";
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVerifyTokenRequest(): VerifyTokenRequest {
  return { token: "" };
}

export const VerifyTokenRequest: MessageFns<VerifyTokenRequest> = {
  encode(message: VerifyTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVerifyTokenRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.token = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<VerifyTokenRequest>, I>>(base?: I): VerifyTokenRequest {
    return VerifyTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyTokenRequest>, I>>(object: I): VerifyTokenRequest {
    const message = createBaseVerifyTokenRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseVerifyTokenResponse(): VerifyTokenResponse {
  return { valid: false, userId: "", email: "", tokenType: "", isStaff: false, errors: [] };
}

export const VerifyTokenResponse: MessageFns<VerifyTokenResponse> = {
  encode(message: VerifyTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.valid !== false) {
      writer.uint32(8).bool(message.valid);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.tokenType !== "") {
      writer.uint32(34).string(message.tokenType);
    }
    if (message.isStaff !== false) {
      writer.uint32(40).bool(message.isStaff);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVerifyTokenResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.valid = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.userId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.email = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.tokenType = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.isStaff = reader.bool();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<VerifyTokenResponse>, I>>(base?: I): VerifyTokenResponse {
    return VerifyTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyTokenResponse>, I>>(object: I): VerifyTokenResponse {
    const message = createBaseVerifyTokenResponse();
    message.valid = object.valid ?? false;
    message.userId = object.userId ?? "";
    message.email = object.email ?? "";
    message.tokenType = object.tokenType ?? "";
    message.isStaff = object.isStaff ?? false;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCheckPermissionRequest(): CheckPermissionRequest {
  return { userId: "", codename: "" };
}

export const CheckPermissionRequest: MessageFns<CheckPermissionRequest> = {
  encode(message: CheckPermissionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.codename !== "") {
      writer.uint32(18).string(message.codename);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckPermissionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCheckPermissionRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.userId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.codename = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CheckPermissionRequest>, I>>(base?: I): CheckPermissionRequest {
    return CheckPermissionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckPermissionRequest>, I>>(object: I): CheckPermissionRequest {
    const message = createBaseCheckPermissionRequest();
    message.userId = object.userId ?? "";
    message.codename = object.codename ?? "";
    return message;
  },
};

function createBaseCheckPermissionResponse(): CheckPermissionResponse {
  return { allowed: false };
}

export const CheckPermissionResponse: MessageFns<CheckPermissionResponse> = {
  encode(message: CheckPermissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allowed !== false) {
      writer.uint32(8).bool(message.allowed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckPermissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCheckPermissionResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.allowed = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CheckPermissionResponse>, I>>(base?: I): CheckPermissionResponse {
    return CheckPermissionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckPermissionResponse>, I>>(object: I): CheckPermissionResponse {
    const message = createBaseCheckPermissionResponse();
    message.allowed = object.allowed ?? false;
    return message;
  },
};

function createBaseCreateAppTokenRequest(): CreateAppTokenRequest {
  return { appId: 0, name: "" };
}

export const CreateAppTokenRequest: MessageFns<CreateAppTokenRequest> = {
  encode(message: CreateAppTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appId !== 0) {
      writer.uint32(8).int32(message.appId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAppTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateAppTokenRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.appId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.name = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CreateAppTokenRequest>, I>>(base?: I): CreateAppTokenRequest {
    return CreateAppTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAppTokenRequest>, I>>(object: I): CreateAppTokenRequest {
    const message = createBaseCreateAppTokenRequest();
    message.appId = object.appId ?? 0;
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseCreateAppTokenResponse(): CreateAppTokenResponse {
  return { tokenId: 0, token: "", errors: [] };
}

export const CreateAppTokenResponse: MessageFns<CreateAppTokenResponse> = {
  encode(message: CreateAppTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenId !== 0) {
      writer.uint32(8).int32(message.tokenId);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAppTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateAppTokenResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tokenId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.token = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CreateAppTokenResponse>, I>>(base?: I): CreateAppTokenResponse {
    return CreateAppTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAppTokenResponse>, I>>(object: I): CreateAppTokenResponse {
    const message = createBaseCreateAppTokenResponse();
    message.tokenId = object.tokenId ?? 0;
    message.token = object.token ?? "";
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVerifyAppTokenRequest(): VerifyAppTokenRequest {
  return { token: "" };
}

export const VerifyAppTokenRequest: MessageFns<VerifyAppTokenRequest> = {
  encode(message: VerifyAppTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyAppTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVerifyAppTokenRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.token = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<VerifyAppTokenRequest>, I>>(base?: I): VerifyAppTokenRequest {
    return VerifyAppTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyAppTokenRequest>, I>>(object: I): VerifyAppTokenRequest {
    const message = createBaseVerifyAppTokenRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseVerifyAppTokenResponse(): VerifyAppTokenResponse {
  return { valid: false, appId: 0, appName: "" };
}

export const VerifyAppTokenResponse: MessageFns<VerifyAppTokenResponse> = {
  encode(message: VerifyAppTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.valid !== false) {
      writer.uint32(8).bool(message.valid);
    }
    if (message.appId !== 0) {
      writer.uint32(16).int32(message.appId);
    }
    if (message.appName !== "") {
      writer.uint32(26).string(message.appName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyAppTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVerifyAppTokenResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.valid = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.appId = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.appName = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<VerifyAppTokenResponse>, I>>(base?: I): VerifyAppTokenResponse {
    return VerifyAppTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyAppTokenResponse>, I>>(object: I): VerifyAppTokenResponse {
    const message = createBaseVerifyAppTokenResponse();
    message.valid = object.valid ?? false;
    message.appId = object.appId ?? 0;
    message.appName = object.appName ?? "";
    return message;
  },
};

function createBaseRevokeAppTokenRequest(): RevokeAppTokenRequest {
  return { tokenId: 0 };
}

export const RevokeAppTokenRequest: MessageFns<RevokeAppTokenRequest> = {
  encode(message: RevokeAppTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenId !== 0) {
      writer.uint32(8).int32(message.tokenId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeAppTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRevokeAppTokenRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tokenId = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RevokeAppTokenRequest>, I>>(base?: I): RevokeAppTokenRequest {
    return RevokeAppTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeAppTokenRequest>, I>>(object: I): RevokeAppTokenRequest {
    const message = createBaseRevokeAppTokenRequest();
    message.tokenId = object.tokenId ?? 0;
    return message;
  },
};

function createBaseRevokeAppTokenResponse(): RevokeAppTokenResponse {
  return { revoked: false, errors: [] };
}

export const RevokeAppTokenResponse: MessageFns<RevokeAppTokenResponse> = {
  encode(message: RevokeAppTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.revoked !== false) {
      writer.uint32(8).bool(message.revoked);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeAppTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRevokeAppTokenResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.revoked = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RevokeAppTokenResponse>, I>>(base?: I): RevokeAppTokenResponse {
    return RevokeAppTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeAppTokenResponse>, I>>(object: I): RevokeAppTokenResponse {
    const message = createBaseRevokeAppTokenResponse();
    message.revoked = object.revoked ?? false;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

export type AuthServiceService = typeof AuthServiceService;
export const AuthServiceService = {
  login: {
    path: "/rustygod.auth.AuthService/Login" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: LoginRequest): Buffer => Buffer.from(LoginRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LoginRequest => LoginRequest.decode(value),
    responseSerialize: (value: LoginResponse): Buffer => Buffer.from(LoginResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LoginResponse => LoginResponse.decode(value),
  },
  refreshToken: {
    path: "/rustygod.auth.AuthService/RefreshToken" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RefreshTokenRequest): Buffer => Buffer.from(RefreshTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RefreshTokenRequest => RefreshTokenRequest.decode(value),
    responseSerialize: (value: RefreshTokenResponse): Buffer =>
      Buffer.from(RefreshTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RefreshTokenResponse => RefreshTokenResponse.decode(value),
  },
  verifyToken: {
    path: "/rustygod.auth.AuthService/VerifyToken" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: VerifyTokenRequest): Buffer => Buffer.from(VerifyTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyTokenRequest => VerifyTokenRequest.decode(value),
    responseSerialize: (value: VerifyTokenResponse): Buffer => Buffer.from(VerifyTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyTokenResponse => VerifyTokenResponse.decode(value),
  },
  checkPermission: {
    path: "/rustygod.auth.AuthService/CheckPermission" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckPermissionRequest): Buffer =>
      Buffer.from(CheckPermissionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckPermissionRequest => CheckPermissionRequest.decode(value),
    responseSerialize: (value: CheckPermissionResponse): Buffer =>
      Buffer.from(CheckPermissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckPermissionResponse => CheckPermissionResponse.decode(value),
  },
  createAppToken: {
    path: "/rustygod.auth.AuthService/CreateAppToken" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateAppTokenRequest): Buffer =>
      Buffer.from(CreateAppTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateAppTokenRequest => CreateAppTokenRequest.decode(value),
    responseSerialize: (value: CreateAppTokenResponse): Buffer =>
      Buffer.from(CreateAppTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateAppTokenResponse => CreateAppTokenResponse.decode(value),
  },
  verifyAppToken: {
    path: "/rustygod.auth.AuthService/VerifyAppToken" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: VerifyAppTokenRequest): Buffer =>
      Buffer.from(VerifyAppTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyAppTokenRequest => VerifyAppTokenRequest.decode(value),
    responseSerialize: (value: VerifyAppTokenResponse): Buffer =>
      Buffer.from(VerifyAppTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyAppTokenResponse => VerifyAppTokenResponse.decode(value),
  },
  revokeAppToken: {
    path: "/rustygod.auth.AuthService/RevokeAppToken" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RevokeAppTokenRequest): Buffer =>
      Buffer.from(RevokeAppTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RevokeAppTokenRequest => RevokeAppTokenRequest.decode(value),
    responseSerialize: (value: RevokeAppTokenResponse): Buffer =>
      Buffer.from(RevokeAppTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RevokeAppTokenResponse => RevokeAppTokenResponse.decode(value),
  },
} as const;

export interface AuthServiceServer extends UntypedServiceImplementation {
  login: handleUnaryCall<LoginRequest, LoginResponse>;
  refreshToken: handleUnaryCall<RefreshTokenRequest, RefreshTokenResponse>;
  verifyToken: handleUnaryCall<VerifyTokenRequest, VerifyTokenResponse>;
  checkPermission: handleUnaryCall<CheckPermissionRequest, CheckPermissionResponse>;
  createAppToken: handleUnaryCall<CreateAppTokenRequest, CreateAppTokenResponse>;
  verifyAppToken: handleUnaryCall<VerifyAppTokenRequest, VerifyAppTokenResponse>;
  revokeAppToken: handleUnaryCall<RevokeAppTokenRequest, RevokeAppTokenResponse>;
}

export interface AuthServiceClient extends Client {
  login(
    request: LoginRequest,
    callback: (error: ServiceError | null, response: LoginResponse) => void,
  ): ClientUnaryCall;
  login(
    request: LoginRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: LoginResponse) => void,
  ): ClientUnaryCall;
  login(
    request: LoginRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LoginResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    callback: (error: ServiceError | null, response: RefreshTokenResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RefreshTokenResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RefreshTokenResponse) => void,
  ): ClientUnaryCall;
  verifyToken(
    request: VerifyTokenRequest,
    callback: (error: ServiceError | null, response: VerifyTokenResponse) => void,
  ): ClientUnaryCall;
  verifyToken(
    request: VerifyTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerifyTokenResponse) => void,
  ): ClientUnaryCall;
  verifyToken(
    request: VerifyTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerifyTokenResponse) => void,
  ): ClientUnaryCall;
  checkPermission(
    request: CheckPermissionRequest,
    callback: (error: ServiceError | null, response: CheckPermissionResponse) => void,
  ): ClientUnaryCall;
  checkPermission(
    request: CheckPermissionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckPermissionResponse) => void,
  ): ClientUnaryCall;
  checkPermission(
    request: CheckPermissionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckPermissionResponse) => void,
  ): ClientUnaryCall;
  createAppToken(
    request: CreateAppTokenRequest,
    callback: (error: ServiceError | null, response: CreateAppTokenResponse) => void,
  ): ClientUnaryCall;
  createAppToken(
    request: CreateAppTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateAppTokenResponse) => void,
  ): ClientUnaryCall;
  createAppToken(
    request: CreateAppTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateAppTokenResponse) => void,
  ): ClientUnaryCall;
  verifyAppToken(
    request: VerifyAppTokenRequest,
    callback: (error: ServiceError | null, response: VerifyAppTokenResponse) => void,
  ): ClientUnaryCall;
  verifyAppToken(
    request: VerifyAppTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerifyAppTokenResponse) => void,
  ): ClientUnaryCall;
  verifyAppToken(
    request: VerifyAppTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerifyAppTokenResponse) => void,
  ): ClientUnaryCall;
  revokeAppToken(
    request: RevokeAppTokenRequest,
    callback: (error: ServiceError | null, response: RevokeAppTokenResponse) => void,
  ): ClientUnaryCall;
  revokeAppToken(
    request: RevokeAppTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RevokeAppTokenResponse) => void,
  ): ClientUnaryCall;
  revokeAppToken(
    request: RevokeAppTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RevokeAppTokenResponse) => void,
  ): ClientUnaryCall;
}

export const AuthServiceClient = makeGenericClientConstructor(
  AuthServiceService,
  "rustygod.auth.AuthService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AuthServiceClient;
  service: typeof AuthServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
