// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.19.1
// source: giftcard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Error } from "./common.js";

export const protobufPackage = "rustygod.giftcard";

/** Mirrors saleor/giftcard GiftCard rows + event-sourced mutations. */
export interface GiftCardInfo {
  code: string;
  currency: string;
  initialBalance: string;
  currentBalance: string;
  isActive: boolean;
  /** YYYY-MM-DD or empty */
  expiryDate: string;
  createdByEmail: string;
}

export interface IssueGiftCardRequest {
  initialBalance: string;
  currency: string;
  createdByEmail: string;
  /** YYYY-MM-DD or empty */
  expiryDate: string;
}

export interface IssueGiftCardResponse {
  giftCard: GiftCardInfo | undefined;
  errors: Error[];
}

export interface GetGiftCardRequest {
  code: string;
}

export interface GetGiftCardResponse {
  giftCard: GiftCardInfo | undefined;
  errors: Error[];
}

export interface CheckoutGiftCardRequest {
  /** checkout token (UUID) */
  checkoutId: string;
  code: string;
}

export interface CheckoutGiftCardResponse {
  giftCard: GiftCardInfo | undefined;
  errors: Error[];
}

export interface CheckoutBalanceRequest {
  checkoutId: string;
}

export interface CheckoutBalanceResponse {
  currency: string;
  balance: string;
  errors: Error[];
}

export interface RedeemGiftCardRequest {
  code: string;
  /** optional UUID */
  orderId: string;
  amount: string;
}

export interface RedeemGiftCardResponse {
  amountTaken: string;
  giftCard: GiftCardInfo | undefined;
  errors: Error[];
}

export interface BalanceMutationRequest {
  code: string;
  /** adjust: new balance; refund: amount to add back */
  amount: string;
  /** refund only, optional UUID */
  orderId: string;
}

export interface BalanceMutationResponse {
  giftCard: GiftCardInfo | undefined;
  errors: Error[];
}

export interface SetActiveRequest {
  code: string;
  active: boolean;
}

export interface SetActiveResponse {
  giftCard: GiftCardInfo | undefined;
  errors: Error[];
}

function createBaseGiftCardInfo(): GiftCardInfo {
  return {
    code: "",
    currency: "",
    initialBalance: "",
    currentBalance: "",
    isActive: false,
    expiryDate: "",
    createdByEmail: "",
  };
}

export const GiftCardInfo: MessageFns<GiftCardInfo> = {
  encode(message: GiftCardInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.currency !== "") {
      writer.uint32(18).string(message.currency);
    }
    if (message.initialBalance !== "") {
      writer.uint32(26).string(message.initialBalance);
    }
    if (message.currentBalance !== "") {
      writer.uint32(34).string(message.currentBalance);
    }
    if (message.isActive !== false) {
      writer.uint32(40).bool(message.isActive);
    }
    if (message.expiryDate !== "") {
      writer.uint32(50).string(message.expiryDate);
    }
    if (message.createdByEmail !== "") {
      writer.uint32(58).string(message.createdByEmail);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GiftCardInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGiftCardInfo();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.currency = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.initialBalance = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.currentBalance = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.isActive = reader.bool();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.expiryDate = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.createdByEmail = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GiftCardInfo>, I>>(base?: I): GiftCardInfo {
    return GiftCardInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GiftCardInfo>, I>>(object: I): GiftCardInfo {
    const message = createBaseGiftCardInfo();
    message.code = object.code ?? "";
    message.currency = object.currency ?? "";
    message.initialBalance = object.initialBalance ?? "";
    message.currentBalance = object.currentBalance ?? "";
    message.isActive = object.isActive ?? false;
    message.expiryDate = object.expiryDate ?? "";
    message.createdByEmail = object.createdByEmail ?? "";
    return message;
  },
};

function createBaseIssueGiftCardRequest(): IssueGiftCardRequest {
  return { initialBalance: "", currency: "", createdByEmail: "", expiryDate: "" };
}

export const IssueGiftCardRequest: MessageFns<IssueGiftCardRequest> = {
  encode(message: IssueGiftCardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.initialBalance !== "") {
      writer.uint32(10).string(message.initialBalance);
    }
    if (message.currency !== "") {
      writer.uint32(18).string(message.currency);
    }
    if (message.createdByEmail !== "") {
      writer.uint32(26).string(message.createdByEmail);
    }
    if (message.expiryDate !== "") {
      writer.uint32(34).string(message.expiryDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IssueGiftCardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseIssueGiftCardRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.initialBalance = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.currency = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.createdByEmail = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.expiryDate = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<IssueGiftCardRequest>, I>>(base?: I): IssueGiftCardRequest {
    return IssueGiftCardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IssueGiftCardRequest>, I>>(object: I): IssueGiftCardRequest {
    const message = createBaseIssueGiftCardRequest();
    message.initialBalance = object.initialBalance ?? "";
    message.currency = object.currency ?? "";
    message.createdByEmail = object.createdByEmail ?? "";
    message.expiryDate = object.expiryDate ?? "";
    return message;
  },
};

function createBaseIssueGiftCardResponse(): IssueGiftCardResponse {
  return { giftCard: undefined, errors: [] };
}

export const IssueGiftCardResponse: MessageFns<IssueGiftCardResponse> = {
  encode(message: IssueGiftCardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.giftCard !== undefined) {
      GiftCardInfo.encode(message.giftCard, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IssueGiftCardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseIssueGiftCardResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.giftCard = GiftCardInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<IssueGiftCardResponse>, I>>(base?: I): IssueGiftCardResponse {
    return IssueGiftCardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IssueGiftCardResponse>, I>>(object: I): IssueGiftCardResponse {
    const message = createBaseIssueGiftCardResponse();
    message.giftCard = (object.giftCard !== undefined && object.giftCard !== null)
      ? GiftCardInfo.fromPartial(object.giftCard)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetGiftCardRequest(): GetGiftCardRequest {
  return { code: "" };
}

export const GetGiftCardRequest: MessageFns<GetGiftCardRequest> = {
  encode(message: GetGiftCardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGiftCardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetGiftCardRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.code = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GetGiftCardRequest>, I>>(base?: I): GetGiftCardRequest {
    return GetGiftCardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGiftCardRequest>, I>>(object: I): GetGiftCardRequest {
    const message = createBaseGetGiftCardRequest();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseGetGiftCardResponse(): GetGiftCardResponse {
  return { giftCard: undefined, errors: [] };
}

export const GetGiftCardResponse: MessageFns<GetGiftCardResponse> = {
  encode(message: GetGiftCardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.giftCard !== undefined) {
      GiftCardInfo.encode(message.giftCard, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGiftCardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetGiftCardResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.giftCard = GiftCardInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GetGiftCardResponse>, I>>(base?: I): GetGiftCardResponse {
    return GetGiftCardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGiftCardResponse>, I>>(object: I): GetGiftCardResponse {
    const message = createBaseGetGiftCardResponse();
    message.giftCard = (object.giftCard !== undefined && object.giftCard !== null)
      ? GiftCardInfo.fromPartial(object.giftCard)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCheckoutGiftCardRequest(): CheckoutGiftCardRequest {
  return { checkoutId: "", code: "" };
}

export const CheckoutGiftCardRequest: MessageFns<CheckoutGiftCardRequest> = {
  encode(message: CheckoutGiftCardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.checkoutId !== "") {
      writer.uint32(10).string(message.checkoutId);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckoutGiftCardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCheckoutGiftCardRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.checkoutId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.code = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CheckoutGiftCardRequest>, I>>(base?: I): CheckoutGiftCardRequest {
    return CheckoutGiftCardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckoutGiftCardRequest>, I>>(object: I): CheckoutGiftCardRequest {
    const message = createBaseCheckoutGiftCardRequest();
    message.checkoutId = object.checkoutId ?? "";
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseCheckoutGiftCardResponse(): CheckoutGiftCardResponse {
  return { giftCard: undefined, errors: [] };
}

export const CheckoutGiftCardResponse: MessageFns<CheckoutGiftCardResponse> = {
  encode(message: CheckoutGiftCardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.giftCard !== undefined) {
      GiftCardInfo.encode(message.giftCard, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckoutGiftCardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCheckoutGiftCardResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.giftCard = GiftCardInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CheckoutGiftCardResponse>, I>>(base?: I): CheckoutGiftCardResponse {
    return CheckoutGiftCardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckoutGiftCardResponse>, I>>(object: I): CheckoutGiftCardResponse {
    const message = createBaseCheckoutGiftCardResponse();
    message.giftCard = (object.giftCard !== undefined && object.giftCard !== null)
      ? GiftCardInfo.fromPartial(object.giftCard)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCheckoutBalanceRequest(): CheckoutBalanceRequest {
  return { checkoutId: "" };
}

export const CheckoutBalanceRequest: MessageFns<CheckoutBalanceRequest> = {
  encode(message: CheckoutBalanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.checkoutId !== "") {
      writer.uint32(10).string(message.checkoutId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckoutBalanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCheckoutBalanceRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.checkoutId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CheckoutBalanceRequest>, I>>(base?: I): CheckoutBalanceRequest {
    return CheckoutBalanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckoutBalanceRequest>, I>>(object: I): CheckoutBalanceRequest {
    const message = createBaseCheckoutBalanceRequest();
    message.checkoutId = object.checkoutId ?? "";
    return message;
  },
};

function createBaseCheckoutBalanceResponse(): CheckoutBalanceResponse {
  return { currency: "", balance: "", errors: [] };
}

export const CheckoutBalanceResponse: MessageFns<CheckoutBalanceResponse> = {
  encode(message: CheckoutBalanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currency !== "") {
      writer.uint32(10).string(message.currency);
    }
    if (message.balance !== "") {
      writer.uint32(18).string(message.balance);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckoutBalanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCheckoutBalanceResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.currency = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.balance = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CheckoutBalanceResponse>, I>>(base?: I): CheckoutBalanceResponse {
    return CheckoutBalanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckoutBalanceResponse>, I>>(object: I): CheckoutBalanceResponse {
    const message = createBaseCheckoutBalanceResponse();
    message.currency = object.currency ?? "";
    message.balance = object.balance ?? "";
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRedeemGiftCardRequest(): RedeemGiftCardRequest {
  return { code: "", orderId: "", amount: "" };
}

export const RedeemGiftCardRequest: MessageFns<RedeemGiftCardRequest> = {
  encode(message: RedeemGiftCardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RedeemGiftCardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRedeemGiftCardRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.amount = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RedeemGiftCardRequest>, I>>(base?: I): RedeemGiftCardRequest {
    return RedeemGiftCardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RedeemGiftCardRequest>, I>>(object: I): RedeemGiftCardRequest {
    const message = createBaseRedeemGiftCardRequest();
    message.code = object.code ?? "";
    message.orderId = object.orderId ?? "";
    message.amount = object.amount ?? "";
    return message;
  },
};

function createBaseRedeemGiftCardResponse(): RedeemGiftCardResponse {
  return { amountTaken: "", giftCard: undefined, errors: [] };
}

export const RedeemGiftCardResponse: MessageFns<RedeemGiftCardResponse> = {
  encode(message: RedeemGiftCardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amountTaken !== "") {
      writer.uint32(10).string(message.amountTaken);
    }
    if (message.giftCard !== undefined) {
      GiftCardInfo.encode(message.giftCard, writer.uint32(18).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RedeemGiftCardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRedeemGiftCardResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.amountTaken = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.giftCard = GiftCardInfo.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RedeemGiftCardResponse>, I>>(base?: I): RedeemGiftCardResponse {
    return RedeemGiftCardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RedeemGiftCardResponse>, I>>(object: I): RedeemGiftCardResponse {
    const message = createBaseRedeemGiftCardResponse();
    message.amountTaken = object.amountTaken ?? "";
    message.giftCard = (object.giftCard !== undefined && object.giftCard !== null)
      ? GiftCardInfo.fromPartial(object.giftCard)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBalanceMutationRequest(): BalanceMutationRequest {
  return { code: "", amount: "", orderId: "" };
}

export const BalanceMutationRequest: MessageFns<BalanceMutationRequest> = {
  encode(message: BalanceMutationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.orderId !== "") {
      writer.uint32(26).string(message.orderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceMutationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBalanceMutationRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.amount = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<BalanceMutationRequest>, I>>(base?: I): BalanceMutationRequest {
    return BalanceMutationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceMutationRequest>, I>>(object: I): BalanceMutationRequest {
    const message = createBaseBalanceMutationRequest();
    message.code = object.code ?? "";
    message.amount = object.amount ?? "";
    message.orderId = object.orderId ?? "";
    return message;
  },
};

function createBaseBalanceMutationResponse(): BalanceMutationResponse {
  return { giftCard: undefined, errors: [] };
}

export const BalanceMutationResponse: MessageFns<BalanceMutationResponse> = {
  encode(message: BalanceMutationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.giftCard !== undefined) {
      GiftCardInfo.encode(message.giftCard, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceMutationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBalanceMutationResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.giftCard = GiftCardInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<BalanceMutationResponse>, I>>(base?: I): BalanceMutationResponse {
    return BalanceMutationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceMutationResponse>, I>>(object: I): BalanceMutationResponse {
    const message = createBaseBalanceMutationResponse();
    message.giftCard = (object.giftCard !== undefined && object.giftCard !== null)
      ? GiftCardInfo.fromPartial(object.giftCard)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSetActiveRequest(): SetActiveRequest {
  return { code: "", active: false };
}

export const SetActiveRequest: MessageFns<SetActiveRequest> = {
  encode(message: SetActiveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.active !== false) {
      writer.uint32(16).bool(message.active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetActiveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSetActiveRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.active = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SetActiveRequest>, I>>(base?: I): SetActiveRequest {
    return SetActiveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetActiveRequest>, I>>(object: I): SetActiveRequest {
    const message = createBaseSetActiveRequest();
    message.code = object.code ?? "";
    message.active = object.active ?? false;
    return message;
  },
};

function createBaseSetActiveResponse(): SetActiveResponse {
  return { giftCard: undefined, errors: [] };
}

export const SetActiveResponse: MessageFns<SetActiveResponse> = {
  encode(message: SetActiveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.giftCard !== undefined) {
      GiftCardInfo.encode(message.giftCard, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetActiveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSetActiveResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.giftCard = GiftCardInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SetActiveResponse>, I>>(base?: I): SetActiveResponse {
    return SetActiveResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetActiveResponse>, I>>(object: I): SetActiveResponse {
    const message = createBaseSetActiveResponse();
    message.giftCard = (object.giftCard !== undefined && object.giftCard !== null)
      ? GiftCardInfo.fromPartial(object.giftCard)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

export type GiftCardServiceService = typeof GiftCardServiceService;
export const GiftCardServiceService = {
  issue: {
    path: "/rustygod.giftcard.GiftCardService/Issue" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: IssueGiftCardRequest): Buffer => Buffer.from(IssueGiftCardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): IssueGiftCardRequest => IssueGiftCardRequest.decode(value),
    responseSerialize: (value: IssueGiftCardResponse): Buffer =>
      Buffer.from(IssueGiftCardResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): IssueGiftCardResponse => IssueGiftCardResponse.decode(value),
  },
  getByCode: {
    path: "/rustygod.giftcard.GiftCardService/GetByCode" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetGiftCardRequest): Buffer => Buffer.from(GetGiftCardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetGiftCardRequest => GetGiftCardRequest.decode(value),
    responseSerialize: (value: GetGiftCardResponse): Buffer => Buffer.from(GetGiftCardResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetGiftCardResponse => GetGiftCardResponse.decode(value),
  },
  attachToCheckout: {
    path: "/rustygod.giftcard.GiftCardService/AttachToCheckout" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckoutGiftCardRequest): Buffer =>
      Buffer.from(CheckoutGiftCardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckoutGiftCardRequest => CheckoutGiftCardRequest.decode(value),
    responseSerialize: (value: CheckoutGiftCardResponse): Buffer =>
      Buffer.from(CheckoutGiftCardResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckoutGiftCardResponse => CheckoutGiftCardResponse.decode(value),
  },
  detachFromCheckout: {
    path: "/rustygod.giftcard.GiftCardService/DetachFromCheckout" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckoutGiftCardRequest): Buffer =>
      Buffer.from(CheckoutGiftCardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckoutGiftCardRequest => CheckoutGiftCardRequest.decode(value),
    responseSerialize: (value: CheckoutGiftCardResponse): Buffer =>
      Buffer.from(CheckoutGiftCardResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckoutGiftCardResponse => CheckoutGiftCardResponse.decode(value),
  },
  checkoutBalance: {
    path: "/rustygod.giftcard.GiftCardService/CheckoutBalance" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckoutBalanceRequest): Buffer =>
      Buffer.from(CheckoutBalanceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckoutBalanceRequest => CheckoutBalanceRequest.decode(value),
    responseSerialize: (value: CheckoutBalanceResponse): Buffer =>
      Buffer.from(CheckoutBalanceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckoutBalanceResponse => CheckoutBalanceResponse.decode(value),
  },
  redeem: {
    path: "/rustygod.giftcard.GiftCardService/Redeem" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RedeemGiftCardRequest): Buffer =>
      Buffer.from(RedeemGiftCardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RedeemGiftCardRequest => RedeemGiftCardRequest.decode(value),
    responseSerialize: (value: RedeemGiftCardResponse): Buffer =>
      Buffer.from(RedeemGiftCardResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RedeemGiftCardResponse => RedeemGiftCardResponse.decode(value),
  },
  adjustBalance: {
    path: "/rustygod.giftcard.GiftCardService/AdjustBalance" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: BalanceMutationRequest): Buffer =>
      Buffer.from(BalanceMutationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BalanceMutationRequest => BalanceMutationRequest.decode(value),
    responseSerialize: (value: BalanceMutationResponse): Buffer =>
      Buffer.from(BalanceMutationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BalanceMutationResponse => BalanceMutationResponse.decode(value),
  },
  refund: {
    path: "/rustygod.giftcard.GiftCardService/Refund" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: BalanceMutationRequest): Buffer =>
      Buffer.from(BalanceMutationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BalanceMutationRequest => BalanceMutationRequest.decode(value),
    responseSerialize: (value: BalanceMutationResponse): Buffer =>
      Buffer.from(BalanceMutationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BalanceMutationResponse => BalanceMutationResponse.decode(value),
  },
  setActive: {
    path: "/rustygod.giftcard.GiftCardService/SetActive" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SetActiveRequest): Buffer => Buffer.from(SetActiveRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SetActiveRequest => SetActiveRequest.decode(value),
    responseSerialize: (value: SetActiveResponse): Buffer => Buffer.from(SetActiveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SetActiveResponse => SetActiveResponse.decode(value),
  },
} as const;

export interface GiftCardServiceServer extends UntypedServiceImplementation {
  issue: handleUnaryCall<IssueGiftCardRequest, IssueGiftCardResponse>;
  getByCode: handleUnaryCall<GetGiftCardRequest, GetGiftCardResponse>;
  attachToCheckout: handleUnaryCall<CheckoutGiftCardRequest, CheckoutGiftCardResponse>;
  detachFromCheckout: handleUnaryCall<CheckoutGiftCardRequest, CheckoutGiftCardResponse>;
  checkoutBalance: handleUnaryCall<CheckoutBalanceRequest, CheckoutBalanceResponse>;
  redeem: handleUnaryCall<RedeemGiftCardRequest, RedeemGiftCardResponse>;
  adjustBalance: handleUnaryCall<BalanceMutationRequest, BalanceMutationResponse>;
  refund: handleUnaryCall<BalanceMutationRequest, BalanceMutationResponse>;
  setActive: handleUnaryCall<SetActiveRequest, SetActiveResponse>;
}

export interface GiftCardServiceClient extends Client {
  issue(
    request: IssueGiftCardRequest,
    callback: (error: ServiceError | null, response: IssueGiftCardResponse) => void,
  ): ClientUnaryCall;
  issue(
    request: IssueGiftCardRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: IssueGiftCardResponse) => void,
  ): ClientUnaryCall;
  issue(
    request: IssueGiftCardRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: IssueGiftCardResponse) => void,
  ): ClientUnaryCall;
  getByCode(
    request: GetGiftCardRequest,
    callback: (error: ServiceError | null, response: GetGiftCardResponse) => void,
  ): ClientUnaryCall;
  getByCode(
    request: GetGiftCardRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetGiftCardResponse) => void,
  ): ClientUnaryCall;
  getByCode(
    request: GetGiftCardRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetGiftCardResponse) => void,
  ): ClientUnaryCall;
  attachToCheckout(
    request: CheckoutGiftCardRequest,
    callback: (error: ServiceError | null, response: CheckoutGiftCardResponse) => void,
  ): ClientUnaryCall;
  attachToCheckout(
    request: CheckoutGiftCardRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckoutGiftCardResponse) => void,
  ): ClientUnaryCall;
  attachToCheckout(
    request: CheckoutGiftCardRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckoutGiftCardResponse) => void,
  ): ClientUnaryCall;
  detachFromCheckout(
    request: CheckoutGiftCardRequest,
    callback: (error: ServiceError | null, response: CheckoutGiftCardResponse) => void,
  ): ClientUnaryCall;
  detachFromCheckout(
    request: CheckoutGiftCardRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckoutGiftCardResponse) => void,
  ): ClientUnaryCall;
  detachFromCheckout(
    request: CheckoutGiftCardRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckoutGiftCardResponse) => void,
  ): ClientUnaryCall;
  checkoutBalance(
    request: CheckoutBalanceRequest,
    callback: (error: ServiceError | null, response: CheckoutBalanceResponse) => void,
  ): ClientUnaryCall;
  checkoutBalance(
    request: CheckoutBalanceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckoutBalanceResponse) => void,
  ): ClientUnaryCall;
  checkoutBalance(
    request: CheckoutBalanceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckoutBalanceResponse) => void,
  ): ClientUnaryCall;
  redeem(
    request: RedeemGiftCardRequest,
    callback: (error: ServiceError | null, response: RedeemGiftCardResponse) => void,
  ): ClientUnaryCall;
  redeem(
    request: RedeemGiftCardRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RedeemGiftCardResponse) => void,
  ): ClientUnaryCall;
  redeem(
    request: RedeemGiftCardRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RedeemGiftCardResponse) => void,
  ): ClientUnaryCall;
  adjustBalance(
    request: BalanceMutationRequest,
    callback: (error: ServiceError | null, response: BalanceMutationResponse) => void,
  ): ClientUnaryCall;
  adjustBalance(
    request: BalanceMutationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BalanceMutationResponse) => void,
  ): ClientUnaryCall;
  adjustBalance(
    request: BalanceMutationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BalanceMutationResponse) => void,
  ): ClientUnaryCall;
  refund(
    request: BalanceMutationRequest,
    callback: (error: ServiceError | null, response: BalanceMutationResponse) => void,
  ): ClientUnaryCall;
  refund(
    request: BalanceMutationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BalanceMutationResponse) => void,
  ): ClientUnaryCall;
  refund(
    request: BalanceMutationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BalanceMutationResponse) => void,
  ): ClientUnaryCall;
  setActive(
    request: SetActiveRequest,
    callback: (error: ServiceError | null, response: SetActiveResponse) => void,
  ): ClientUnaryCall;
  setActive(
    request: SetActiveRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SetActiveResponse) => void,
  ): ClientUnaryCall;
  setActive(
    request: SetActiveRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SetActiveResponse) => void,
  ): ClientUnaryCall;
}

export const GiftCardServiceClient = makeGenericClientConstructor(
  GiftCardServiceService,
  "rustygod.giftcard.GiftCardService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): GiftCardServiceClient;
  service: typeof GiftCardServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
