// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.19.1
// source: invoice.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Error } from "./common.js";

export const protobufPackage = "rustygod.invoice";

/**
 * Staff invoices over Django's invoice_* tables.
 * Mirrors saleor/graphql/invoice/mutations/.
 */
export interface InvoiceInfo {
  id: number;
  orderId: string;
  status: string;
  number: string;
  url: string;
}

export interface RequestInvoiceRequest {
  orderId: string;
  /** optional */
  number: string;
}

export interface RequestInvoiceResponse {
  invoice: InvoiceInfo | undefined;
  errors: Error[];
}

export interface FulfillInvoiceRequest {
  id: number;
  number: string;
  url: string;
}

export interface FulfillInvoiceResponse {
  invoice: InvoiceInfo | undefined;
  errors: Error[];
}

export interface InvoiceIdRequest {
  id: number;
}

export interface InvoiceResponse {
  invoice: InvoiceInfo | undefined;
  errors: Error[];
}

export interface SendInvoiceRequest {
  id: number;
  email: string;
}

export interface SendInvoiceResponse {
  invoice: InvoiceInfo | undefined;
  errors: Error[];
}

export interface ListReadyInvoicesRequest {
  orderId: string;
}

export interface ListReadyInvoicesResponse {
  invoices: InvoiceInfo[];
  errors: Error[];
}

function createBaseInvoiceInfo(): InvoiceInfo {
  return { id: 0, orderId: "", status: "", number: "", url: "" };
}

export const InvoiceInfo: MessageFns<InvoiceInfo> = {
  encode(message: InvoiceInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.number !== "") {
      writer.uint32(34).string(message.number);
    }
    if (message.url !== "") {
      writer.uint32(42).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvoiceInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseInvoiceInfo();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.number = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.url = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<InvoiceInfo>, I>>(base?: I): InvoiceInfo {
    return InvoiceInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvoiceInfo>, I>>(object: I): InvoiceInfo {
    const message = createBaseInvoiceInfo();
    message.id = object.id ?? 0;
    message.orderId = object.orderId ?? "";
    message.status = object.status ?? "";
    message.number = object.number ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseRequestInvoiceRequest(): RequestInvoiceRequest {
  return { orderId: "", number: "" };
}

export const RequestInvoiceRequest: MessageFns<RequestInvoiceRequest> = {
  encode(message: RequestInvoiceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.number !== "") {
      writer.uint32(18).string(message.number);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestInvoiceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRequestInvoiceRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.number = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RequestInvoiceRequest>, I>>(base?: I): RequestInvoiceRequest {
    return RequestInvoiceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestInvoiceRequest>, I>>(object: I): RequestInvoiceRequest {
    const message = createBaseRequestInvoiceRequest();
    message.orderId = object.orderId ?? "";
    message.number = object.number ?? "";
    return message;
  },
};

function createBaseRequestInvoiceResponse(): RequestInvoiceResponse {
  return { invoice: undefined, errors: [] };
}

export const RequestInvoiceResponse: MessageFns<RequestInvoiceResponse> = {
  encode(message: RequestInvoiceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invoice !== undefined) {
      InvoiceInfo.encode(message.invoice, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestInvoiceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRequestInvoiceResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.invoice = InvoiceInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RequestInvoiceResponse>, I>>(base?: I): RequestInvoiceResponse {
    return RequestInvoiceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestInvoiceResponse>, I>>(object: I): RequestInvoiceResponse {
    const message = createBaseRequestInvoiceResponse();
    message.invoice = (object.invoice !== undefined && object.invoice !== null)
      ? InvoiceInfo.fromPartial(object.invoice)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFulfillInvoiceRequest(): FulfillInvoiceRequest {
  return { id: 0, number: "", url: "" };
}

export const FulfillInvoiceRequest: MessageFns<FulfillInvoiceRequest> = {
  encode(message: FulfillInvoiceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.number !== "") {
      writer.uint32(18).string(message.number);
    }
    if (message.url !== "") {
      writer.uint32(26).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FulfillInvoiceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFulfillInvoiceRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.number = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.url = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FulfillInvoiceRequest>, I>>(base?: I): FulfillInvoiceRequest {
    return FulfillInvoiceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FulfillInvoiceRequest>, I>>(object: I): FulfillInvoiceRequest {
    const message = createBaseFulfillInvoiceRequest();
    message.id = object.id ?? 0;
    message.number = object.number ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseFulfillInvoiceResponse(): FulfillInvoiceResponse {
  return { invoice: undefined, errors: [] };
}

export const FulfillInvoiceResponse: MessageFns<FulfillInvoiceResponse> = {
  encode(message: FulfillInvoiceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invoice !== undefined) {
      InvoiceInfo.encode(message.invoice, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FulfillInvoiceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFulfillInvoiceResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.invoice = InvoiceInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FulfillInvoiceResponse>, I>>(base?: I): FulfillInvoiceResponse {
    return FulfillInvoiceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FulfillInvoiceResponse>, I>>(object: I): FulfillInvoiceResponse {
    const message = createBaseFulfillInvoiceResponse();
    message.invoice = (object.invoice !== undefined && object.invoice !== null)
      ? InvoiceInfo.fromPartial(object.invoice)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseInvoiceIdRequest(): InvoiceIdRequest {
  return { id: 0 };
}

export const InvoiceIdRequest: MessageFns<InvoiceIdRequest> = {
  encode(message: InvoiceIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvoiceIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseInvoiceIdRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<InvoiceIdRequest>, I>>(base?: I): InvoiceIdRequest {
    return InvoiceIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvoiceIdRequest>, I>>(object: I): InvoiceIdRequest {
    const message = createBaseInvoiceIdRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseInvoiceResponse(): InvoiceResponse {
  return { invoice: undefined, errors: [] };
}

export const InvoiceResponse: MessageFns<InvoiceResponse> = {
  encode(message: InvoiceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invoice !== undefined) {
      InvoiceInfo.encode(message.invoice, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvoiceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseInvoiceResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.invoice = InvoiceInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<InvoiceResponse>, I>>(base?: I): InvoiceResponse {
    return InvoiceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvoiceResponse>, I>>(object: I): InvoiceResponse {
    const message = createBaseInvoiceResponse();
    message.invoice = (object.invoice !== undefined && object.invoice !== null)
      ? InvoiceInfo.fromPartial(object.invoice)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSendInvoiceRequest(): SendInvoiceRequest {
  return { id: 0, email: "" };
}

export const SendInvoiceRequest: MessageFns<SendInvoiceRequest> = {
  encode(message: SendInvoiceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendInvoiceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSendInvoiceRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.email = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SendInvoiceRequest>, I>>(base?: I): SendInvoiceRequest {
    return SendInvoiceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendInvoiceRequest>, I>>(object: I): SendInvoiceRequest {
    const message = createBaseSendInvoiceRequest();
    message.id = object.id ?? 0;
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseSendInvoiceResponse(): SendInvoiceResponse {
  return { invoice: undefined, errors: [] };
}

export const SendInvoiceResponse: MessageFns<SendInvoiceResponse> = {
  encode(message: SendInvoiceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invoice !== undefined) {
      InvoiceInfo.encode(message.invoice, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendInvoiceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSendInvoiceResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.invoice = InvoiceInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SendInvoiceResponse>, I>>(base?: I): SendInvoiceResponse {
    return SendInvoiceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendInvoiceResponse>, I>>(object: I): SendInvoiceResponse {
    const message = createBaseSendInvoiceResponse();
    message.invoice = (object.invoice !== undefined && object.invoice !== null)
      ? InvoiceInfo.fromPartial(object.invoice)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListReadyInvoicesRequest(): ListReadyInvoicesRequest {
  return { orderId: "" };
}

export const ListReadyInvoicesRequest: MessageFns<ListReadyInvoicesRequest> = {
  encode(message: ListReadyInvoicesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListReadyInvoicesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListReadyInvoicesRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ListReadyInvoicesRequest>, I>>(base?: I): ListReadyInvoicesRequest {
    return ListReadyInvoicesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListReadyInvoicesRequest>, I>>(object: I): ListReadyInvoicesRequest {
    const message = createBaseListReadyInvoicesRequest();
    message.orderId = object.orderId ?? "";
    return message;
  },
};

function createBaseListReadyInvoicesResponse(): ListReadyInvoicesResponse {
  return { invoices: [], errors: [] };
}

export const ListReadyInvoicesResponse: MessageFns<ListReadyInvoicesResponse> = {
  encode(message: ListReadyInvoicesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.invoices) {
      InvoiceInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListReadyInvoicesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListReadyInvoicesResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.invoices.push(InvoiceInfo.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ListReadyInvoicesResponse>, I>>(base?: I): ListReadyInvoicesResponse {
    return ListReadyInvoicesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListReadyInvoicesResponse>, I>>(object: I): ListReadyInvoicesResponse {
    const message = createBaseListReadyInvoicesResponse();
    message.invoices = object.invoices?.map((e) => InvoiceInfo.fromPartial(e)) || [];
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

export type InvoiceServiceService = typeof InvoiceServiceService;
export const InvoiceServiceService = {
  requestInvoice: {
    path: "/rustygod.invoice.InvoiceService/RequestInvoice" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RequestInvoiceRequest): Buffer =>
      Buffer.from(RequestInvoiceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RequestInvoiceRequest => RequestInvoiceRequest.decode(value),
    responseSerialize: (value: RequestInvoiceResponse): Buffer =>
      Buffer.from(RequestInvoiceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RequestInvoiceResponse => RequestInvoiceResponse.decode(value),
  },
  fulfillInvoice: {
    path: "/rustygod.invoice.InvoiceService/FulfillInvoice" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: FulfillInvoiceRequest): Buffer =>
      Buffer.from(FulfillInvoiceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): FulfillInvoiceRequest => FulfillInvoiceRequest.decode(value),
    responseSerialize: (value: FulfillInvoiceResponse): Buffer =>
      Buffer.from(FulfillInvoiceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FulfillInvoiceResponse => FulfillInvoiceResponse.decode(value),
  },
  sendInvoice: {
    path: "/rustygod.invoice.InvoiceService/SendInvoice" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SendInvoiceRequest): Buffer => Buffer.from(SendInvoiceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendInvoiceRequest => SendInvoiceRequest.decode(value),
    responseSerialize: (value: SendInvoiceResponse): Buffer => Buffer.from(SendInvoiceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendInvoiceResponse => SendInvoiceResponse.decode(value),
  },
  requestDeletion: {
    path: "/rustygod.invoice.InvoiceService/RequestDeletion" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: InvoiceIdRequest): Buffer => Buffer.from(InvoiceIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): InvoiceIdRequest => InvoiceIdRequest.decode(value),
    responseSerialize: (value: InvoiceResponse): Buffer => Buffer.from(InvoiceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InvoiceResponse => InvoiceResponse.decode(value),
  },
  deleteInvoice: {
    path: "/rustygod.invoice.InvoiceService/DeleteInvoice" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: InvoiceIdRequest): Buffer => Buffer.from(InvoiceIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): InvoiceIdRequest => InvoiceIdRequest.decode(value),
    responseSerialize: (value: InvoiceResponse): Buffer => Buffer.from(InvoiceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InvoiceResponse => InvoiceResponse.decode(value),
  },
  listReady: {
    path: "/rustygod.invoice.InvoiceService/ListReady" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListReadyInvoicesRequest): Buffer =>
      Buffer.from(ListReadyInvoicesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListReadyInvoicesRequest => ListReadyInvoicesRequest.decode(value),
    responseSerialize: (value: ListReadyInvoicesResponse): Buffer =>
      Buffer.from(ListReadyInvoicesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListReadyInvoicesResponse => ListReadyInvoicesResponse.decode(value),
  },
} as const;

export interface InvoiceServiceServer extends UntypedServiceImplementation {
  requestInvoice: handleUnaryCall<RequestInvoiceRequest, RequestInvoiceResponse>;
  fulfillInvoice: handleUnaryCall<FulfillInvoiceRequest, FulfillInvoiceResponse>;
  sendInvoice: handleUnaryCall<SendInvoiceRequest, SendInvoiceResponse>;
  requestDeletion: handleUnaryCall<InvoiceIdRequest, InvoiceResponse>;
  deleteInvoice: handleUnaryCall<InvoiceIdRequest, InvoiceResponse>;
  listReady: handleUnaryCall<ListReadyInvoicesRequest, ListReadyInvoicesResponse>;
}

export interface InvoiceServiceClient extends Client {
  requestInvoice(
    request: RequestInvoiceRequest,
    callback: (error: ServiceError | null, response: RequestInvoiceResponse) => void,
  ): ClientUnaryCall;
  requestInvoice(
    request: RequestInvoiceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RequestInvoiceResponse) => void,
  ): ClientUnaryCall;
  requestInvoice(
    request: RequestInvoiceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RequestInvoiceResponse) => void,
  ): ClientUnaryCall;
  fulfillInvoice(
    request: FulfillInvoiceRequest,
    callback: (error: ServiceError | null, response: FulfillInvoiceResponse) => void,
  ): ClientUnaryCall;
  fulfillInvoice(
    request: FulfillInvoiceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FulfillInvoiceResponse) => void,
  ): ClientUnaryCall;
  fulfillInvoice(
    request: FulfillInvoiceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FulfillInvoiceResponse) => void,
  ): ClientUnaryCall;
  sendInvoice(
    request: SendInvoiceRequest,
    callback: (error: ServiceError | null, response: SendInvoiceResponse) => void,
  ): ClientUnaryCall;
  sendInvoice(
    request: SendInvoiceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SendInvoiceResponse) => void,
  ): ClientUnaryCall;
  sendInvoice(
    request: SendInvoiceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SendInvoiceResponse) => void,
  ): ClientUnaryCall;
  requestDeletion(
    request: InvoiceIdRequest,
    callback: (error: ServiceError | null, response: InvoiceResponse) => void,
  ): ClientUnaryCall;
  requestDeletion(
    request: InvoiceIdRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: InvoiceResponse) => void,
  ): ClientUnaryCall;
  requestDeletion(
    request: InvoiceIdRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: InvoiceResponse) => void,
  ): ClientUnaryCall;
  deleteInvoice(
    request: InvoiceIdRequest,
    callback: (error: ServiceError | null, response: InvoiceResponse) => void,
  ): ClientUnaryCall;
  deleteInvoice(
    request: InvoiceIdRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: InvoiceResponse) => void,
  ): ClientUnaryCall;
  deleteInvoice(
    request: InvoiceIdRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: InvoiceResponse) => void,
  ): ClientUnaryCall;
  listReady(
    request: ListReadyInvoicesRequest,
    callback: (error: ServiceError | null, response: ListReadyInvoicesResponse) => void,
  ): ClientUnaryCall;
  listReady(
    request: ListReadyInvoicesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListReadyInvoicesResponse) => void,
  ): ClientUnaryCall;
  listReady(
    request: ListReadyInvoicesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListReadyInvoicesResponse) => void,
  ): ClientUnaryCall;
}

export const InvoiceServiceClient = makeGenericClientConstructor(
  InvoiceServiceService,
  "rustygod.invoice.InvoiceService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): InvoiceServiceClient;
  service: typeof InvoiceServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
