// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.19.1
// source: order.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Error, Money, PageInfo } from "./common.js";

export const protobufPackage = "rustygod.order";

/** Mirrors saleor/order models: Order + OrderLine + Fulfillment. */
export interface OrderLine {
  variantId: string;
  productName: string;
  quantity: number;
  unitPrice: Money | undefined;
  totalPrice: Money | undefined;
}

export interface Order {
  id: string;
  number: string;
  channel: string;
  email: string;
  status: string;
  lines: OrderLine[];
  total: Money | undefined;
  currency: string;
  createdAt: string;
}

export interface GetOrderRequest {
  id: string;
}

export interface GetOrderResponse {
  order: Order | undefined;
  errors: Error[];
}

export interface ReconcileOrderRequest {
  id: string;
}

export interface ReconCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface ReconcileOrderResponse {
  checks: ReconCheck[];
  allOk: boolean;
  errors: Error[];
}

export interface CancelOrderRequest {
  id: string;
}

export interface CancelOrderResponse {
  status: string;
  errors: Error[];
}

/** Mirrors saleor OrderGrantRefundCreate: decision first, money on execute. */
export interface GrantRefundLineInput {
  orderLineId: string;
  quantity: number;
}

export interface CreateGrantedRefundRequest {
  orderId: string;
  /** 0 = none linked */
  transactionItemId: number;
  /** empty = derive from lines+shipping */
  amount: string;
  lines: GrantRefundLineInput[];
  reason: string;
  shippingCostsIncluded: boolean;
}

export interface GrantedRefundLineInfo {
  orderLineId: string;
  quantity: number;
}

export interface CreateGrantedRefundResponse {
  grantedRefundId: number;
  amount: string;
  status: string;
  lines: GrantedRefundLineInfo[];
  errors: Error[];
}

export interface ExecuteGrantedRefundRequest {
  grantedRefundId: number;
  idempotencyKey: string;
}

export interface ExecuteGrantedRefundResponse {
  status: string;
  replayed: boolean;
  errors: Error[];
}

export interface GetGrantedRefundRequest {
  grantedRefundId: number;
}

export interface GetGrantedRefundResponse {
  grantedRefundId: number;
  orderId: string;
  amount: string;
  status: string;
  reason: string;
  lines: GrantedRefundLineInfo[];
  errors: Error[];
}

export interface ListOrdersRequest {
  first: number;
  after: string;
  status: string;
}

export interface ListOrdersResponse {
  orders: Order[];
  pageInfo: PageInfo | undefined;
}

/**
 * Mirrors saleor/order fulfillments: fulfillment_order auto-increments,
 * lines cap at the unfulfilled remainder, stock moves with the lines.
 */
export interface FulfillLineInput {
  orderLineId: string;
  quantity: number;
  stockId: string;
}

export interface FulfillmentLineInfo {
  orderLineId: string;
  quantity: number;
  stockId: string;
}

export interface FulfillmentInfo {
  id: string;
  orderId: string;
  fulfillmentOrder: number;
  status: string;
  trackingNumber: string;
  lines: FulfillmentLineInfo[];
}

export interface CreateFulfillmentRequest {
  orderId: string;
  lines: FulfillLineInput[];
  trackingNumber: string;
}

export interface CancelFulfillmentRequest {
  fulfillmentId: string;
}

export interface RefundFulfillmentRequest {
  orderId: string;
  lines: FulfillLineInput[];
  reason: string;
}

export interface FulfillmentResponse {
  fulfillment: FulfillmentInfo | undefined;
  errors: Error[];
}

export interface ListFulfillmentsRequest {
  orderId: string;
}

export interface ListFulfillmentsResponse {
  fulfillments: FulfillmentInfo[];
}

function createBaseOrderLine(): OrderLine {
  return { variantId: "", productName: "", quantity: 0, unitPrice: undefined, totalPrice: undefined };
}

export const OrderLine: MessageFns<OrderLine> = {
  encode(message: OrderLine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variantId !== "") {
      writer.uint32(10).string(message.variantId);
    }
    if (message.productName !== "") {
      writer.uint32(18).string(message.productName);
    }
    if (message.quantity !== 0) {
      writer.uint32(24).int32(message.quantity);
    }
    if (message.unitPrice !== undefined) {
      Money.encode(message.unitPrice, writer.uint32(34).fork()).join();
    }
    if (message.totalPrice !== undefined) {
      Money.encode(message.totalPrice, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderLine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOrderLine();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.variantId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.productName = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.quantity = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.unitPrice = Money.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.totalPrice = Money.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<OrderLine>, I>>(base?: I): OrderLine {
    return OrderLine.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderLine>, I>>(object: I): OrderLine {
    const message = createBaseOrderLine();
    message.variantId = object.variantId ?? "";
    message.productName = object.productName ?? "";
    message.quantity = object.quantity ?? 0;
    message.unitPrice = (object.unitPrice !== undefined && object.unitPrice !== null)
      ? Money.fromPartial(object.unitPrice)
      : undefined;
    message.totalPrice = (object.totalPrice !== undefined && object.totalPrice !== null)
      ? Money.fromPartial(object.totalPrice)
      : undefined;
    return message;
  },
};

function createBaseOrder(): Order {
  return {
    id: "",
    number: "",
    channel: "",
    email: "",
    status: "",
    lines: [],
    total: undefined,
    currency: "",
    createdAt: "",
  };
}

export const Order: MessageFns<Order> = {
  encode(message: Order, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.number !== "") {
      writer.uint32(18).string(message.number);
    }
    if (message.channel !== "") {
      writer.uint32(26).string(message.channel);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    for (const v of message.lines) {
      OrderLine.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.total !== undefined) {
      Money.encode(message.total, writer.uint32(58).fork()).join();
    }
    if (message.currency !== "") {
      writer.uint32(66).string(message.currency);
    }
    if (message.createdAt !== "") {
      writer.uint32(74).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Order {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOrder();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.number = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.channel = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.email = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.lines.push(OrderLine.decode(reader, reader.uint32()));
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.total = Money.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.currency = reader.string();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.createdAt = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Order>, I>>(base?: I): Order {
    return Order.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Order>, I>>(object: I): Order {
    const message = createBaseOrder();
    message.id = object.id ?? "";
    message.number = object.number ?? "";
    message.channel = object.channel ?? "";
    message.email = object.email ?? "";
    message.status = object.status ?? "";
    message.lines = object.lines?.map((e) => OrderLine.fromPartial(e)) || [];
    message.total = (object.total !== undefined && object.total !== null) ? Money.fromPartial(object.total) : undefined;
    message.currency = object.currency ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseGetOrderRequest(): GetOrderRequest {
  return { id: "" };
}

export const GetOrderRequest: MessageFns<GetOrderRequest> = {
  encode(message: GetOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetOrderRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GetOrderRequest>, I>>(base?: I): GetOrderRequest {
    return GetOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrderRequest>, I>>(object: I): GetOrderRequest {
    const message = createBaseGetOrderRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetOrderResponse(): GetOrderResponse {
  return { order: undefined, errors: [] };
}

export const GetOrderResponse: MessageFns<GetOrderResponse> = {
  encode(message: GetOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order !== undefined) {
      Order.encode(message.order, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetOrderResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.order = Order.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GetOrderResponse>, I>>(base?: I): GetOrderResponse {
    return GetOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrderResponse>, I>>(object: I): GetOrderResponse {
    const message = createBaseGetOrderResponse();
    message.order = (object.order !== undefined && object.order !== null) ? Order.fromPartial(object.order) : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseReconcileOrderRequest(): ReconcileOrderRequest {
  return { id: "" };
}

export const ReconcileOrderRequest: MessageFns<ReconcileOrderRequest> = {
  encode(message: ReconcileOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReconcileOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReconcileOrderRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ReconcileOrderRequest>, I>>(base?: I): ReconcileOrderRequest {
    return ReconcileOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReconcileOrderRequest>, I>>(object: I): ReconcileOrderRequest {
    const message = createBaseReconcileOrderRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseReconCheck(): ReconCheck {
  return { name: "", ok: false, detail: "" };
}

export const ReconCheck: MessageFns<ReconCheck> = {
  encode(message: ReconCheck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.ok !== false) {
      writer.uint32(16).bool(message.ok);
    }
    if (message.detail !== "") {
      writer.uint32(26).string(message.detail);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReconCheck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReconCheck();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.ok = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.detail = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ReconCheck>, I>>(base?: I): ReconCheck {
    return ReconCheck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReconCheck>, I>>(object: I): ReconCheck {
    const message = createBaseReconCheck();
    message.name = object.name ?? "";
    message.ok = object.ok ?? false;
    message.detail = object.detail ?? "";
    return message;
  },
};

function createBaseReconcileOrderResponse(): ReconcileOrderResponse {
  return { checks: [], allOk: false, errors: [] };
}

export const ReconcileOrderResponse: MessageFns<ReconcileOrderResponse> = {
  encode(message: ReconcileOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.checks) {
      ReconCheck.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.allOk !== false) {
      writer.uint32(16).bool(message.allOk);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReconcileOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReconcileOrderResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.checks.push(ReconCheck.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.allOk = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ReconcileOrderResponse>, I>>(base?: I): ReconcileOrderResponse {
    return ReconcileOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReconcileOrderResponse>, I>>(object: I): ReconcileOrderResponse {
    const message = createBaseReconcileOrderResponse();
    message.checks = object.checks?.map((e) => ReconCheck.fromPartial(e)) || [];
    message.allOk = object.allOk ?? false;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCancelOrderRequest(): CancelOrderRequest {
  return { id: "" };
}

export const CancelOrderRequest: MessageFns<CancelOrderRequest> = {
  encode(message: CancelOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCancelOrderRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CancelOrderRequest>, I>>(base?: I): CancelOrderRequest {
    return CancelOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOrderRequest>, I>>(object: I): CancelOrderRequest {
    const message = createBaseCancelOrderRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseCancelOrderResponse(): CancelOrderResponse {
  return { status: "", errors: [] };
}

export const CancelOrderResponse: MessageFns<CancelOrderResponse> = {
  encode(message: CancelOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCancelOrderResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CancelOrderResponse>, I>>(base?: I): CancelOrderResponse {
    return CancelOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOrderResponse>, I>>(object: I): CancelOrderResponse {
    const message = createBaseCancelOrderResponse();
    message.status = object.status ?? "";
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGrantRefundLineInput(): GrantRefundLineInput {
  return { orderLineId: "", quantity: 0 };
}

export const GrantRefundLineInput: MessageFns<GrantRefundLineInput> = {
  encode(message: GrantRefundLineInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderLineId !== "") {
      writer.uint32(10).string(message.orderLineId);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrantRefundLineInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGrantRefundLineInput();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderLineId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.quantity = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GrantRefundLineInput>, I>>(base?: I): GrantRefundLineInput {
    return GrantRefundLineInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrantRefundLineInput>, I>>(object: I): GrantRefundLineInput {
    const message = createBaseGrantRefundLineInput();
    message.orderLineId = object.orderLineId ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseCreateGrantedRefundRequest(): CreateGrantedRefundRequest {
  return { orderId: "", transactionItemId: 0, amount: "", lines: [], reason: "", shippingCostsIncluded: false };
}

export const CreateGrantedRefundRequest: MessageFns<CreateGrantedRefundRequest> = {
  encode(message: CreateGrantedRefundRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.transactionItemId !== 0) {
      writer.uint32(16).int32(message.transactionItemId);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    for (const v of message.lines) {
      GrantRefundLineInput.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.reason !== "") {
      writer.uint32(42).string(message.reason);
    }
    if (message.shippingCostsIncluded !== false) {
      writer.uint32(48).bool(message.shippingCostsIncluded);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateGrantedRefundRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateGrantedRefundRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.transactionItemId = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.amount = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.lines.push(GrantRefundLineInput.decode(reader, reader.uint32()));
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.reason = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.shippingCostsIncluded = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CreateGrantedRefundRequest>, I>>(base?: I): CreateGrantedRefundRequest {
    return CreateGrantedRefundRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateGrantedRefundRequest>, I>>(object: I): CreateGrantedRefundRequest {
    const message = createBaseCreateGrantedRefundRequest();
    message.orderId = object.orderId ?? "";
    message.transactionItemId = object.transactionItemId ?? 0;
    message.amount = object.amount ?? "";
    message.lines = object.lines?.map((e) => GrantRefundLineInput.fromPartial(e)) || [];
    message.reason = object.reason ?? "";
    message.shippingCostsIncluded = object.shippingCostsIncluded ?? false;
    return message;
  },
};

function createBaseGrantedRefundLineInfo(): GrantedRefundLineInfo {
  return { orderLineId: "", quantity: 0 };
}

export const GrantedRefundLineInfo: MessageFns<GrantedRefundLineInfo> = {
  encode(message: GrantedRefundLineInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderLineId !== "") {
      writer.uint32(10).string(message.orderLineId);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrantedRefundLineInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGrantedRefundLineInfo();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderLineId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.quantity = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GrantedRefundLineInfo>, I>>(base?: I): GrantedRefundLineInfo {
    return GrantedRefundLineInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrantedRefundLineInfo>, I>>(object: I): GrantedRefundLineInfo {
    const message = createBaseGrantedRefundLineInfo();
    message.orderLineId = object.orderLineId ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseCreateGrantedRefundResponse(): CreateGrantedRefundResponse {
  return { grantedRefundId: 0, amount: "", status: "", lines: [], errors: [] };
}

export const CreateGrantedRefundResponse: MessageFns<CreateGrantedRefundResponse> = {
  encode(message: CreateGrantedRefundResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grantedRefundId !== 0) {
      writer.uint32(8).int32(message.grantedRefundId);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    for (const v of message.lines) {
      GrantedRefundLineInfo.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateGrantedRefundResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateGrantedRefundResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.grantedRefundId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.amount = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.lines.push(GrantedRefundLineInfo.decode(reader, reader.uint32()));
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CreateGrantedRefundResponse>, I>>(base?: I): CreateGrantedRefundResponse {
    return CreateGrantedRefundResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateGrantedRefundResponse>, I>>(object: I): CreateGrantedRefundResponse {
    const message = createBaseCreateGrantedRefundResponse();
    message.grantedRefundId = object.grantedRefundId ?? 0;
    message.amount = object.amount ?? "";
    message.status = object.status ?? "";
    message.lines = object.lines?.map((e) => GrantedRefundLineInfo.fromPartial(e)) || [];
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExecuteGrantedRefundRequest(): ExecuteGrantedRefundRequest {
  return { grantedRefundId: 0, idempotencyKey: "" };
}

export const ExecuteGrantedRefundRequest: MessageFns<ExecuteGrantedRefundRequest> = {
  encode(message: ExecuteGrantedRefundRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grantedRefundId !== 0) {
      writer.uint32(8).int32(message.grantedRefundId);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(18).string(message.idempotencyKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteGrantedRefundRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseExecuteGrantedRefundRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.grantedRefundId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.idempotencyKey = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ExecuteGrantedRefundRequest>, I>>(base?: I): ExecuteGrantedRefundRequest {
    return ExecuteGrantedRefundRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteGrantedRefundRequest>, I>>(object: I): ExecuteGrantedRefundRequest {
    const message = createBaseExecuteGrantedRefundRequest();
    message.grantedRefundId = object.grantedRefundId ?? 0;
    message.idempotencyKey = object.idempotencyKey ?? "";
    return message;
  },
};

function createBaseExecuteGrantedRefundResponse(): ExecuteGrantedRefundResponse {
  return { status: "", replayed: false, errors: [] };
}

export const ExecuteGrantedRefundResponse: MessageFns<ExecuteGrantedRefundResponse> = {
  encode(message: ExecuteGrantedRefundResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.replayed !== false) {
      writer.uint32(16).bool(message.replayed);
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteGrantedRefundResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseExecuteGrantedRefundResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.replayed = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ExecuteGrantedRefundResponse>, I>>(base?: I): ExecuteGrantedRefundResponse {
    return ExecuteGrantedRefundResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteGrantedRefundResponse>, I>>(object: I): ExecuteGrantedRefundResponse {
    const message = createBaseExecuteGrantedRefundResponse();
    message.status = object.status ?? "";
    message.replayed = object.replayed ?? false;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetGrantedRefundRequest(): GetGrantedRefundRequest {
  return { grantedRefundId: 0 };
}

export const GetGrantedRefundRequest: MessageFns<GetGrantedRefundRequest> = {
  encode(message: GetGrantedRefundRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grantedRefundId !== 0) {
      writer.uint32(8).int32(message.grantedRefundId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGrantedRefundRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetGrantedRefundRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.grantedRefundId = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GetGrantedRefundRequest>, I>>(base?: I): GetGrantedRefundRequest {
    return GetGrantedRefundRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGrantedRefundRequest>, I>>(object: I): GetGrantedRefundRequest {
    const message = createBaseGetGrantedRefundRequest();
    message.grantedRefundId = object.grantedRefundId ?? 0;
    return message;
  },
};

function createBaseGetGrantedRefundResponse(): GetGrantedRefundResponse {
  return { grantedRefundId: 0, orderId: "", amount: "", status: "", reason: "", lines: [], errors: [] };
}

export const GetGrantedRefundResponse: MessageFns<GetGrantedRefundResponse> = {
  encode(message: GetGrantedRefundResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grantedRefundId !== 0) {
      writer.uint32(8).int32(message.grantedRefundId);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.reason !== "") {
      writer.uint32(42).string(message.reason);
    }
    for (const v of message.lines) {
      GrantedRefundLineInfo.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGrantedRefundResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetGrantedRefundResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.grantedRefundId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.amount = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.reason = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.lines.push(GrantedRefundLineInfo.decode(reader, reader.uint32()));
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GetGrantedRefundResponse>, I>>(base?: I): GetGrantedRefundResponse {
    return GetGrantedRefundResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGrantedRefundResponse>, I>>(object: I): GetGrantedRefundResponse {
    const message = createBaseGetGrantedRefundResponse();
    message.grantedRefundId = object.grantedRefundId ?? 0;
    message.orderId = object.orderId ?? "";
    message.amount = object.amount ?? "";
    message.status = object.status ?? "";
    message.reason = object.reason ?? "";
    message.lines = object.lines?.map((e) => GrantedRefundLineInfo.fromPartial(e)) || [];
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListOrdersRequest(): ListOrdersRequest {
  return { first: 0, after: "", status: "" };
}

export const ListOrdersRequest: MessageFns<ListOrdersRequest> = {
  encode(message: ListOrdersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.first !== 0) {
      writer.uint32(8).int32(message.first);
    }
    if (message.after !== "") {
      writer.uint32(18).string(message.after);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListOrdersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListOrdersRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.first = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.after = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.status = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ListOrdersRequest>, I>>(base?: I): ListOrdersRequest {
    return ListOrdersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListOrdersRequest>, I>>(object: I): ListOrdersRequest {
    const message = createBaseListOrdersRequest();
    message.first = object.first ?? 0;
    message.after = object.after ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseListOrdersResponse(): ListOrdersResponse {
  return { orders: [], pageInfo: undefined };
}

export const ListOrdersResponse: MessageFns<ListOrdersResponse> = {
  encode(message: ListOrdersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.orders) {
      Order.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pageInfo !== undefined) {
      PageInfo.encode(message.pageInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListOrdersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListOrdersResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orders.push(Order.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.pageInfo = PageInfo.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ListOrdersResponse>, I>>(base?: I): ListOrdersResponse {
    return ListOrdersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListOrdersResponse>, I>>(object: I): ListOrdersResponse {
    const message = createBaseListOrdersResponse();
    message.orders = object.orders?.map((e) => Order.fromPartial(e)) || [];
    message.pageInfo = (object.pageInfo !== undefined && object.pageInfo !== null)
      ? PageInfo.fromPartial(object.pageInfo)
      : undefined;
    return message;
  },
};

function createBaseFulfillLineInput(): FulfillLineInput {
  return { orderLineId: "", quantity: 0, stockId: "" };
}

export const FulfillLineInput: MessageFns<FulfillLineInput> = {
  encode(message: FulfillLineInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderLineId !== "") {
      writer.uint32(10).string(message.orderLineId);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    if (message.stockId !== "") {
      writer.uint32(26).string(message.stockId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FulfillLineInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFulfillLineInput();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderLineId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.quantity = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.stockId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FulfillLineInput>, I>>(base?: I): FulfillLineInput {
    return FulfillLineInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FulfillLineInput>, I>>(object: I): FulfillLineInput {
    const message = createBaseFulfillLineInput();
    message.orderLineId = object.orderLineId ?? "";
    message.quantity = object.quantity ?? 0;
    message.stockId = object.stockId ?? "";
    return message;
  },
};

function createBaseFulfillmentLineInfo(): FulfillmentLineInfo {
  return { orderLineId: "", quantity: 0, stockId: "" };
}

export const FulfillmentLineInfo: MessageFns<FulfillmentLineInfo> = {
  encode(message: FulfillmentLineInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderLineId !== "") {
      writer.uint32(10).string(message.orderLineId);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    if (message.stockId !== "") {
      writer.uint32(26).string(message.stockId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FulfillmentLineInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFulfillmentLineInfo();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderLineId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.quantity = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.stockId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FulfillmentLineInfo>, I>>(base?: I): FulfillmentLineInfo {
    return FulfillmentLineInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FulfillmentLineInfo>, I>>(object: I): FulfillmentLineInfo {
    const message = createBaseFulfillmentLineInfo();
    message.orderLineId = object.orderLineId ?? "";
    message.quantity = object.quantity ?? 0;
    message.stockId = object.stockId ?? "";
    return message;
  },
};

function createBaseFulfillmentInfo(): FulfillmentInfo {
  return { id: "", orderId: "", fulfillmentOrder: 0, status: "", trackingNumber: "", lines: [] };
}

export const FulfillmentInfo: MessageFns<FulfillmentInfo> = {
  encode(message: FulfillmentInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.fulfillmentOrder !== 0) {
      writer.uint32(24).int32(message.fulfillmentOrder);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.trackingNumber !== "") {
      writer.uint32(42).string(message.trackingNumber);
    }
    for (const v of message.lines) {
      FulfillmentLineInfo.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FulfillmentInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFulfillmentInfo();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.fulfillmentOrder = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.trackingNumber = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.lines.push(FulfillmentLineInfo.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FulfillmentInfo>, I>>(base?: I): FulfillmentInfo {
    return FulfillmentInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FulfillmentInfo>, I>>(object: I): FulfillmentInfo {
    const message = createBaseFulfillmentInfo();
    message.id = object.id ?? "";
    message.orderId = object.orderId ?? "";
    message.fulfillmentOrder = object.fulfillmentOrder ?? 0;
    message.status = object.status ?? "";
    message.trackingNumber = object.trackingNumber ?? "";
    message.lines = object.lines?.map((e) => FulfillmentLineInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateFulfillmentRequest(): CreateFulfillmentRequest {
  return { orderId: "", lines: [], trackingNumber: "" };
}

export const CreateFulfillmentRequest: MessageFns<CreateFulfillmentRequest> = {
  encode(message: CreateFulfillmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    for (const v of message.lines) {
      FulfillLineInput.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.trackingNumber !== "") {
      writer.uint32(26).string(message.trackingNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateFulfillmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateFulfillmentRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.lines.push(FulfillLineInput.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.trackingNumber = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CreateFulfillmentRequest>, I>>(base?: I): CreateFulfillmentRequest {
    return CreateFulfillmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateFulfillmentRequest>, I>>(object: I): CreateFulfillmentRequest {
    const message = createBaseCreateFulfillmentRequest();
    message.orderId = object.orderId ?? "";
    message.lines = object.lines?.map((e) => FulfillLineInput.fromPartial(e)) || [];
    message.trackingNumber = object.trackingNumber ?? "";
    return message;
  },
};

function createBaseCancelFulfillmentRequest(): CancelFulfillmentRequest {
  return { fulfillmentId: "" };
}

export const CancelFulfillmentRequest: MessageFns<CancelFulfillmentRequest> = {
  encode(message: CancelFulfillmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fulfillmentId !== "") {
      writer.uint32(10).string(message.fulfillmentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelFulfillmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCancelFulfillmentRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fulfillmentId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CancelFulfillmentRequest>, I>>(base?: I): CancelFulfillmentRequest {
    return CancelFulfillmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelFulfillmentRequest>, I>>(object: I): CancelFulfillmentRequest {
    const message = createBaseCancelFulfillmentRequest();
    message.fulfillmentId = object.fulfillmentId ?? "";
    return message;
  },
};

function createBaseRefundFulfillmentRequest(): RefundFulfillmentRequest {
  return { orderId: "", lines: [], reason: "" };
}

export const RefundFulfillmentRequest: MessageFns<RefundFulfillmentRequest> = {
  encode(message: RefundFulfillmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    for (const v of message.lines) {
      FulfillLineInput.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefundFulfillmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRefundFulfillmentRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.lines.push(FulfillLineInput.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.reason = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RefundFulfillmentRequest>, I>>(base?: I): RefundFulfillmentRequest {
    return RefundFulfillmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefundFulfillmentRequest>, I>>(object: I): RefundFulfillmentRequest {
    const message = createBaseRefundFulfillmentRequest();
    message.orderId = object.orderId ?? "";
    message.lines = object.lines?.map((e) => FulfillLineInput.fromPartial(e)) || [];
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseFulfillmentResponse(): FulfillmentResponse {
  return { fulfillment: undefined, errors: [] };
}

export const FulfillmentResponse: MessageFns<FulfillmentResponse> = {
  encode(message: FulfillmentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fulfillment !== undefined) {
      FulfillmentInfo.encode(message.fulfillment, writer.uint32(10).fork()).join();
    }
    for (const v of message.errors) {
      Error.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FulfillmentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFulfillmentResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fulfillment = FulfillmentInfo.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errors.push(Error.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FulfillmentResponse>, I>>(base?: I): FulfillmentResponse {
    return FulfillmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FulfillmentResponse>, I>>(object: I): FulfillmentResponse {
    const message = createBaseFulfillmentResponse();
    message.fulfillment = (object.fulfillment !== undefined && object.fulfillment !== null)
      ? FulfillmentInfo.fromPartial(object.fulfillment)
      : undefined;
    message.errors = object.errors?.map((e) => Error.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListFulfillmentsRequest(): ListFulfillmentsRequest {
  return { orderId: "" };
}

export const ListFulfillmentsRequest: MessageFns<ListFulfillmentsRequest> = {
  encode(message: ListFulfillmentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFulfillmentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListFulfillmentsRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.orderId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ListFulfillmentsRequest>, I>>(base?: I): ListFulfillmentsRequest {
    return ListFulfillmentsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListFulfillmentsRequest>, I>>(object: I): ListFulfillmentsRequest {
    const message = createBaseListFulfillmentsRequest();
    message.orderId = object.orderId ?? "";
    return message;
  },
};

function createBaseListFulfillmentsResponse(): ListFulfillmentsResponse {
  return { fulfillments: [] };
}

export const ListFulfillmentsResponse: MessageFns<ListFulfillmentsResponse> = {
  encode(message: ListFulfillmentsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.fulfillments) {
      FulfillmentInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFulfillmentsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListFulfillmentsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fulfillments.push(FulfillmentInfo.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ListFulfillmentsResponse>, I>>(base?: I): ListFulfillmentsResponse {
    return ListFulfillmentsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListFulfillmentsResponse>, I>>(object: I): ListFulfillmentsResponse {
    const message = createBaseListFulfillmentsResponse();
    message.fulfillments = object.fulfillments?.map((e) => FulfillmentInfo.fromPartial(e)) || [];
    return message;
  },
};

export type OrderServiceService = typeof OrderServiceService;
export const OrderServiceService = {
  getOrder: {
    path: "/rustygod.order.OrderService/GetOrder" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetOrderRequest): Buffer => Buffer.from(GetOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetOrderRequest => GetOrderRequest.decode(value),
    responseSerialize: (value: GetOrderResponse): Buffer => Buffer.from(GetOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetOrderResponse => GetOrderResponse.decode(value),
  },
  listOrders: {
    path: "/rustygod.order.OrderService/ListOrders" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListOrdersRequest): Buffer => Buffer.from(ListOrdersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListOrdersRequest => ListOrdersRequest.decode(value),
    responseSerialize: (value: ListOrdersResponse): Buffer => Buffer.from(ListOrdersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListOrdersResponse => ListOrdersResponse.decode(value),
  },
  createFulfillment: {
    path: "/rustygod.order.OrderService/CreateFulfillment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateFulfillmentRequest): Buffer =>
      Buffer.from(CreateFulfillmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateFulfillmentRequest => CreateFulfillmentRequest.decode(value),
    responseSerialize: (value: FulfillmentResponse): Buffer => Buffer.from(FulfillmentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FulfillmentResponse => FulfillmentResponse.decode(value),
  },
  cancelFulfillment: {
    path: "/rustygod.order.OrderService/CancelFulfillment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CancelFulfillmentRequest): Buffer =>
      Buffer.from(CancelFulfillmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CancelFulfillmentRequest => CancelFulfillmentRequest.decode(value),
    responseSerialize: (value: FulfillmentResponse): Buffer => Buffer.from(FulfillmentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FulfillmentResponse => FulfillmentResponse.decode(value),
  },
  refundFulfillment: {
    path: "/rustygod.order.OrderService/RefundFulfillment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RefundFulfillmentRequest): Buffer =>
      Buffer.from(RefundFulfillmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RefundFulfillmentRequest => RefundFulfillmentRequest.decode(value),
    responseSerialize: (value: FulfillmentResponse): Buffer => Buffer.from(FulfillmentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FulfillmentResponse => FulfillmentResponse.decode(value),
  },
  listFulfillments: {
    path: "/rustygod.order.OrderService/ListFulfillments" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListFulfillmentsRequest): Buffer =>
      Buffer.from(ListFulfillmentsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListFulfillmentsRequest => ListFulfillmentsRequest.decode(value),
    responseSerialize: (value: ListFulfillmentsResponse): Buffer =>
      Buffer.from(ListFulfillmentsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListFulfillmentsResponse => ListFulfillmentsResponse.decode(value),
  },
  reconcileOrder: {
    path: "/rustygod.order.OrderService/ReconcileOrder" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ReconcileOrderRequest): Buffer =>
      Buffer.from(ReconcileOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ReconcileOrderRequest => ReconcileOrderRequest.decode(value),
    responseSerialize: (value: ReconcileOrderResponse): Buffer =>
      Buffer.from(ReconcileOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ReconcileOrderResponse => ReconcileOrderResponse.decode(value),
  },
  cancelOrder: {
    path: "/rustygod.order.OrderService/CancelOrder" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CancelOrderRequest): Buffer => Buffer.from(CancelOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CancelOrderRequest => CancelOrderRequest.decode(value),
    responseSerialize: (value: CancelOrderResponse): Buffer => Buffer.from(CancelOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CancelOrderResponse => CancelOrderResponse.decode(value),
  },
  createGrantedRefund: {
    path: "/rustygod.order.OrderService/CreateGrantedRefund" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateGrantedRefundRequest): Buffer =>
      Buffer.from(CreateGrantedRefundRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateGrantedRefundRequest => CreateGrantedRefundRequest.decode(value),
    responseSerialize: (value: CreateGrantedRefundResponse): Buffer =>
      Buffer.from(CreateGrantedRefundResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateGrantedRefundResponse => CreateGrantedRefundResponse.decode(value),
  },
  executeGrantedRefund: {
    path: "/rustygod.order.OrderService/ExecuteGrantedRefund" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ExecuteGrantedRefundRequest): Buffer =>
      Buffer.from(ExecuteGrantedRefundRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExecuteGrantedRefundRequest => ExecuteGrantedRefundRequest.decode(value),
    responseSerialize: (value: ExecuteGrantedRefundResponse): Buffer =>
      Buffer.from(ExecuteGrantedRefundResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ExecuteGrantedRefundResponse => ExecuteGrantedRefundResponse.decode(value),
  },
  getGrantedRefund: {
    path: "/rustygod.order.OrderService/GetGrantedRefund" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetGrantedRefundRequest): Buffer =>
      Buffer.from(GetGrantedRefundRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetGrantedRefundRequest => GetGrantedRefundRequest.decode(value),
    responseSerialize: (value: GetGrantedRefundResponse): Buffer =>
      Buffer.from(GetGrantedRefundResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetGrantedRefundResponse => GetGrantedRefundResponse.decode(value),
  },
} as const;

export interface OrderServiceServer extends UntypedServiceImplementation {
  getOrder: handleUnaryCall<GetOrderRequest, GetOrderResponse>;
  listOrders: handleUnaryCall<ListOrdersRequest, ListOrdersResponse>;
  createFulfillment: handleUnaryCall<CreateFulfillmentRequest, FulfillmentResponse>;
  cancelFulfillment: handleUnaryCall<CancelFulfillmentRequest, FulfillmentResponse>;
  refundFulfillment: handleUnaryCall<RefundFulfillmentRequest, FulfillmentResponse>;
  listFulfillments: handleUnaryCall<ListFulfillmentsRequest, ListFulfillmentsResponse>;
  reconcileOrder: handleUnaryCall<ReconcileOrderRequest, ReconcileOrderResponse>;
  cancelOrder: handleUnaryCall<CancelOrderRequest, CancelOrderResponse>;
  createGrantedRefund: handleUnaryCall<CreateGrantedRefundRequest, CreateGrantedRefundResponse>;
  executeGrantedRefund: handleUnaryCall<ExecuteGrantedRefundRequest, ExecuteGrantedRefundResponse>;
  getGrantedRefund: handleUnaryCall<GetGrantedRefundRequest, GetGrantedRefundResponse>;
}

export interface OrderServiceClient extends Client {
  getOrder(
    request: GetOrderRequest,
    callback: (error: ServiceError | null, response: GetOrderResponse) => void,
  ): ClientUnaryCall;
  getOrder(
    request: GetOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetOrderResponse) => void,
  ): ClientUnaryCall;
  getOrder(
    request: GetOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetOrderResponse) => void,
  ): ClientUnaryCall;
  listOrders(
    request: ListOrdersRequest,
    callback: (error: ServiceError | null, response: ListOrdersResponse) => void,
  ): ClientUnaryCall;
  listOrders(
    request: ListOrdersRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListOrdersResponse) => void,
  ): ClientUnaryCall;
  listOrders(
    request: ListOrdersRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListOrdersResponse) => void,
  ): ClientUnaryCall;
  createFulfillment(
    request: CreateFulfillmentRequest,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  createFulfillment(
    request: CreateFulfillmentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  createFulfillment(
    request: CreateFulfillmentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  cancelFulfillment(
    request: CancelFulfillmentRequest,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  cancelFulfillment(
    request: CancelFulfillmentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  cancelFulfillment(
    request: CancelFulfillmentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  refundFulfillment(
    request: RefundFulfillmentRequest,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  refundFulfillment(
    request: RefundFulfillmentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  refundFulfillment(
    request: RefundFulfillmentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FulfillmentResponse) => void,
  ): ClientUnaryCall;
  listFulfillments(
    request: ListFulfillmentsRequest,
    callback: (error: ServiceError | null, response: ListFulfillmentsResponse) => void,
  ): ClientUnaryCall;
  listFulfillments(
    request: ListFulfillmentsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListFulfillmentsResponse) => void,
  ): ClientUnaryCall;
  listFulfillments(
    request: ListFulfillmentsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListFulfillmentsResponse) => void,
  ): ClientUnaryCall;
  reconcileOrder(
    request: ReconcileOrderRequest,
    callback: (error: ServiceError | null, response: ReconcileOrderResponse) => void,
  ): ClientUnaryCall;
  reconcileOrder(
    request: ReconcileOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReconcileOrderResponse) => void,
  ): ClientUnaryCall;
  reconcileOrder(
    request: ReconcileOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReconcileOrderResponse) => void,
  ): ClientUnaryCall;
  cancelOrder(
    request: CancelOrderRequest,
    callback: (error: ServiceError | null, response: CancelOrderResponse) => void,
  ): ClientUnaryCall;
  cancelOrder(
    request: CancelOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CancelOrderResponse) => void,
  ): ClientUnaryCall;
  cancelOrder(
    request: CancelOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CancelOrderResponse) => void,
  ): ClientUnaryCall;
  createGrantedRefund(
    request: CreateGrantedRefundRequest,
    callback: (error: ServiceError | null, response: CreateGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  createGrantedRefund(
    request: CreateGrantedRefundRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  createGrantedRefund(
    request: CreateGrantedRefundRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  executeGrantedRefund(
    request: ExecuteGrantedRefundRequest,
    callback: (error: ServiceError | null, response: ExecuteGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  executeGrantedRefund(
    request: ExecuteGrantedRefundRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExecuteGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  executeGrantedRefund(
    request: ExecuteGrantedRefundRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExecuteGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  getGrantedRefund(
    request: GetGrantedRefundRequest,
    callback: (error: ServiceError | null, response: GetGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  getGrantedRefund(
    request: GetGrantedRefundRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetGrantedRefundResponse) => void,
  ): ClientUnaryCall;
  getGrantedRefund(
    request: GetGrantedRefundRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetGrantedRefundResponse) => void,
  ): ClientUnaryCall;
}

export const OrderServiceClient = makeGenericClientConstructor(
  OrderServiceService,
  "rustygod.order.OrderService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): OrderServiceClient;
  service: typeof OrderServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
