[package]
name = "saleor-rustify-ai"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
sea-orm = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
saleor-rustify-db = { path = "../db" }
saleor-rustify-core = { path = "../core" }

[dev-dependencies]
tokio = { workspace = true }
