//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub is_superuser: bool,
    #[sea_orm(unique)]
    pub email: String,
    pub is_staff: bool,
    pub is_active: bool,
    pub password: String,
    pub date_joined: DateTimeWithTimeZone,
    pub last_login: Option<DateTimeWithTimeZone>,
    pub default_billing_address_id: Option<i32>,
    pub default_shipping_address_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub first_name: String,
    pub last_name: String,
    pub avatar: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub jwt_token_key: String,
    pub language_code: String,
    #[sea_orm(column_type = "Text")]
    pub search_document: String,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    #[sea_orm(unique)]
    pub external_reference: Option<String>,
    pub last_password_reset_request: Option<DateTimeWithTimeZone>,
    pub is_confirmed: bool,
    pub last_confirm_email_request: Option<DateTimeWithTimeZone>,
    pub number_of_orders: i32,
    #[sea_orm(column_type = "custom(\"tsvector\")", nullable)]
    pub search_vector: Option<String>,
    pub customer_type_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_address::Entity",
        from = "Column::DefaultBillingAddressId",
        to = "super::account_address::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountAddress2,
    #[sea_orm(
        belongs_to = "super::account_address::Entity",
        from = "Column::DefaultShippingAddressId",
        to = "super::account_address::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountAddress1,
    #[sea_orm(has_many = "super::account_customerevent::Entity")]
    AccountCustomerevent,
    #[sea_orm(
        belongs_to = "super::account_customertype::Entity",
        from = "Column::CustomerTypeId",
        to = "super::account_customertype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountCustomertype,
    #[sea_orm(has_one = "super::account_staffnotificationrecipient::Entity")]
    AccountStaffnotificationrecipient,
    #[sea_orm(has_many = "super::account_user_addresses::Entity")]
    AccountUserAddresses,
    #[sea_orm(has_many = "super::account_user_groups::Entity")]
    AccountUserGroups,
    #[sea_orm(has_many = "super::account_user_user_permissions::Entity")]
    AccountUserUserPermissions,
    #[sea_orm(has_many = "super::app_appproblem::Entity")]
    AppAppproblem,
    #[sea_orm(has_many = "super::attribute_assigneduserattributevalue::Entity")]
    AttributeAssigneduserattributevalue,
    #[sea_orm(has_many = "super::checkout_checkout::Entity")]
    CheckoutCheckout,
    #[sea_orm(has_many = "super::csv_exportevent::Entity")]
    CsvExportevent,
    #[sea_orm(has_many = "super::csv_exportfile::Entity")]
    CsvExportfile,
    #[sea_orm(has_many = "super::discount_promotionevent::Entity")]
    DiscountPromotionevent,
    #[sea_orm(has_many = "super::giftcard_giftcardevent::Entity")]
    GiftcardGiftcardevent,
    #[sea_orm(has_many = "super::invoice_invoiceevent::Entity")]
    InvoiceInvoiceevent,
    #[sea_orm(has_many = "super::order_order::Entity")]
    OrderOrder,
    #[sea_orm(has_many = "super::order_orderevent::Entity")]
    OrderOrderevent,
    #[sea_orm(has_many = "super::order_ordergrantedrefund::Entity")]
    OrderOrdergrantedrefund,
    #[sea_orm(has_many = "super::payment_transactionevent::Entity")]
    PaymentTransactionevent,
    #[sea_orm(has_many = "super::payment_transactionitem::Entity")]
    PaymentTransactionitem,
    #[sea_orm(has_many = "super::thumbnail_thumbnail::Entity")]
    ThumbnailThumbnail,
}

impl Related<super::account_customerevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountCustomerevent.def()
    }
}

impl Related<super::account_customertype::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountCustomertype.def()
    }
}

impl Related<super::account_staffnotificationrecipient::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountStaffnotificationrecipient.def()
    }
}

impl Related<super::account_user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUserAddresses.def()
    }
}

impl Related<super::account_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUserGroups.def()
    }
}

impl Related<super::account_user_user_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUserUserPermissions.def()
    }
}

impl Related<super::app_appproblem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppproblem.def()
    }
}

impl Related<super::attribute_assigneduserattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssigneduserattributevalue.def()
    }
}

impl Related<super::checkout_checkout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckout.def()
    }
}

impl Related<super::csv_exportevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CsvExportevent.def()
    }
}

impl Related<super::csv_exportfile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CsvExportfile.def()
    }
}

impl Related<super::discount_promotionevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionevent.def()
    }
}

impl Related<super::giftcard_giftcardevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcardevent.def()
    }
}

impl Related<super::invoice_invoiceevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvoiceInvoiceevent.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl Related<super::order_orderevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrderevent.def()
    }
}

impl Related<super::order_ordergrantedrefund::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrdergrantedrefund.def()
    }
}

impl Related<super::payment_transactionevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactionevent.def()
    }
}

impl Related<super::payment_transactionitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactionitem.def()
    }
}

impl Related<super::thumbnail_thumbnail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThumbnailThumbnail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
