//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub restricted_access_to_channels: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_group_channels::Entity")]
    AccountGroupChannels,
    #[sea_orm(has_many = "super::account_group_permissions::Entity")]
    AccountGroupPermissions,
    #[sea_orm(has_many = "super::account_user_groups::Entity")]
    AccountUserGroups,
}

impl Related<super::account_group_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountGroupChannels.def()
    }
}

impl Related<super::account_group_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountGroupPermissions.def()
    }
}

impl Related<super::account_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUserGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
