//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_staffnotificationrecipient")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub staff_email: Option<String>,
    pub active: bool,
    #[sea_orm(unique)]
    pub user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
