//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_address")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
    pub company_name: String,
    pub street_address_1: String,
    pub street_address_2: String,
    pub city: String,
    pub postal_code: String,
    pub country: String,
    pub country_area: String,
    pub phone: String,
    pub city_area: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub validation_skipped: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_user_addresses::Entity")]
    AccountUserAddresses,
    #[sea_orm(has_many = "super::site_sitesettings::Entity")]
    SiteSitesettings,
    #[sea_orm(has_many = "super::warehouse_warehouse::Entity")]
    WarehouseWarehouse,
}

impl Related<super::account_user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUserAddresses.def()
    }
}

impl Related<super::site_sitesettings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteSitesettings.def()
    }
}

impl Related<super::warehouse_warehouse::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseWarehouse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
