//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_customernote")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub is_public: bool,
    pub customer_id: i32,
    pub user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::CustomerId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser2,
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser1,
}

impl ActiveModelBehavior for ActiveModel {}
