//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "app_appinstallation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub message: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub app_name: String,
    pub manifest_url: String,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub brand_logo_default: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_appinstallation_permissions::Entity")]
    AppAppinstallationPermissions,
    #[sea_orm(has_many = "super::thumbnail_thumbnail::Entity")]
    ThumbnailThumbnail,
}

impl Related<super::app_appinstallation_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppinstallationPermissions.def()
    }
}

impl Related<super::thumbnail_thumbnail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThumbnailThumbnail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
