//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "app_app")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub is_active: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub about_app: Option<String>,
    pub app_url: Option<String>,
    pub configuration_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub data_privacy: Option<String>,
    pub data_privacy_url: Option<String>,
    pub homepage_url: Option<String>,
    pub identifier: String,
    pub support_url: Option<String>,
    pub r#type: String,
    pub version: Option<String>,
    pub manifest_url: Option<String>,
    pub audience: Option<String>,
    pub is_installed: bool,
    pub author: Option<String>,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub brand_logo_default: Option<String>,
    pub removed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_customerevent::Entity")]
    AccountCustomerevent,
    #[sea_orm(has_many = "super::app_app_permissions::Entity")]
    AppAppPermissions,
    #[sea_orm(has_many = "super::app_appextension::Entity")]
    AppAppextension,
    #[sea_orm(has_many = "super::app_appproblem::Entity")]
    AppAppproblem,
    #[sea_orm(has_many = "super::app_apptoken::Entity")]
    AppApptoken,
    #[sea_orm(has_many = "super::csv_exportevent::Entity")]
    CsvExportevent,
    #[sea_orm(has_many = "super::csv_exportfile::Entity")]
    CsvExportfile,
    #[sea_orm(has_many = "super::discount_promotionevent::Entity")]
    DiscountPromotionevent,
    #[sea_orm(has_many = "super::giftcard_giftcard::Entity")]
    GiftcardGiftcard,
    #[sea_orm(has_many = "super::giftcard_giftcardevent::Entity")]
    GiftcardGiftcardevent,
    #[sea_orm(has_many = "super::invoice_invoiceevent::Entity")]
    InvoiceInvoiceevent,
    #[sea_orm(has_many = "super::order_orderevent::Entity")]
    OrderOrderevent,
    #[sea_orm(has_many = "super::order_ordergrantedrefund::Entity")]
    OrderOrdergrantedrefund,
    #[sea_orm(has_many = "super::payment_transactionevent::Entity")]
    PaymentTransactionevent,
    #[sea_orm(has_many = "super::payment_transactionitem::Entity")]
    PaymentTransactionitem,
    #[sea_orm(has_many = "super::thumbnail_thumbnail::Entity")]
    ThumbnailThumbnail,
    #[sea_orm(has_many = "super::webhook_webhook::Entity")]
    WebhookWebhook,
}

impl Related<super::account_customerevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountCustomerevent.def()
    }
}

impl Related<super::app_app_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppPermissions.def()
    }
}

impl Related<super::app_appextension::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppextension.def()
    }
}

impl Related<super::app_appproblem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppproblem.def()
    }
}

impl Related<super::app_apptoken::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApptoken.def()
    }
}

impl Related<super::csv_exportevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CsvExportevent.def()
    }
}

impl Related<super::csv_exportfile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CsvExportfile.def()
    }
}

impl Related<super::discount_promotionevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionevent.def()
    }
}

impl Related<super::giftcard_giftcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcard.def()
    }
}

impl Related<super::giftcard_giftcardevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcardevent.def()
    }
}

impl Related<super::invoice_invoiceevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvoiceInvoiceevent.def()
    }
}

impl Related<super::order_orderevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrderevent.def()
    }
}

impl Related<super::order_ordergrantedrefund::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrdergrantedrefund.def()
    }
}

impl Related<super::payment_transactionevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactionevent.def()
    }
}

impl Related<super::payment_transactionitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactionitem.def()
    }
}

impl Related<super::thumbnail_thumbnail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThumbnailThumbnail.def()
    }
}

impl Related<super::webhook_webhook::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookWebhook.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
