//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "app_appinstallation_permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub appinstallation_id: i32,
    pub permission_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_appinstallation::Entity",
        from = "Column::AppinstallationId",
        to = "super::app_appinstallation::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppAppinstallation,
    #[sea_orm(
        belongs_to = "super::permission_permission::Entity",
        from = "Column::PermissionId",
        to = "super::permission_permission::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PermissionPermission,
}

impl Related<super::app_appinstallation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppinstallation.def()
    }
}

impl Related<super::permission_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermissionPermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
