//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "attribute_attributevalue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub attribute_id: i32,
    pub slug: String,
    pub sort_order: Option<i32>,
    pub value: String,
    pub content_type: Option<String>,
    pub file_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub rich_text: Option<Json>,
    pub boolean: Option<bool>,
    pub date_time: Option<DateTimeWithTimeZone>,
    pub reference_page_id: Option<i32>,
    pub reference_product_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub plain_text: Option<String>,
    pub reference_variant_id: Option<i32>,
    #[sea_orm(unique)]
    pub external_reference: Option<String>,
    pub reference_category_id: Option<i32>,
    pub reference_collection_id: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub numeric: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_assignedpageattributevalue::Entity")]
    AttributeAssignedpageattributevalue,
    #[sea_orm(has_many = "super::attribute_assignedproductattributevalue::Entity")]
    AttributeAssignedproductattributevalue,
    #[sea_orm(has_many = "super::attribute_assigneduserattributevalue::Entity")]
    AttributeAssigneduserattributevalue,
    #[sea_orm(has_many = "super::attribute_assignedvariantattributevalue::Entity")]
    AttributeAssignedvariantattributevalue,
    #[sea_orm(
        belongs_to = "super::attribute_attribute::Entity",
        from = "Column::AttributeId",
        to = "super::attribute_attribute::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AttributeAttribute,
    #[sea_orm(has_many = "super::attribute_attributevaluetranslation::Entity")]
    AttributeAttributevaluetranslation,
    #[sea_orm(
        belongs_to = "super::page_page::Entity",
        from = "Column::ReferencePageId",
        to = "super::page_page::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PagePage,
    #[sea_orm(
        belongs_to = "super::product_category::Entity",
        from = "Column::ReferenceCategoryId",
        to = "super::product_category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCategory,
    #[sea_orm(
        belongs_to = "super::product_collection::Entity",
        from = "Column::ReferenceCollectionId",
        to = "super::product_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCollection,
    #[sea_orm(
        belongs_to = "super::product_product::Entity",
        from = "Column::ReferenceProductId",
        to = "super::product_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProduct,
    #[sea_orm(
        belongs_to = "super::product_productvariant::Entity",
        from = "Column::ReferenceVariantId",
        to = "super::product_productvariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariant,
}

impl Related<super::attribute_assignedpageattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssignedpageattributevalue.def()
    }
}

impl Related<super::attribute_assignedproductattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssignedproductattributevalue.def()
    }
}

impl Related<super::attribute_assigneduserattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssigneduserattributevalue.def()
    }
}

impl Related<super::attribute_assignedvariantattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssignedvariantattributevalue.def()
    }
}

impl Related<super::attribute_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttribute.def()
    }
}

impl Related<super::attribute_attributevaluetranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevaluetranslation.def()
    }
}

impl Related<super::page_page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PagePage.def()
    }
}

impl Related<super::product_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategory.def()
    }
}

impl Related<super::product_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollection.def()
    }
}

impl Related<super::product_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProduct.def()
    }
}

impl Related<super::product_productvariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
