//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attribute_assignedvariantattribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub variant_id: i32,
    pub assignment_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_assignedvariantattributevalue::Entity")]
    AttributeAssignedvariantattributevalue,
    #[sea_orm(
        belongs_to = "super::attribute_attributevariant::Entity",
        from = "Column::AssignmentId",
        to = "super::attribute_attributevariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AttributeAttributevariant,
    #[sea_orm(
        belongs_to = "super::product_productvariant::Entity",
        from = "Column::VariantId",
        to = "super::product_productvariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariant,
}

impl Related<super::attribute_assignedvariantattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssignedvariantattributevalue.def()
    }
}

impl Related<super::attribute_attributevariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevariant.def()
    }
}

impl Related<super::product_productvariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
