//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attribute_attributeproduct")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub attribute_id: i32,
    pub product_type_id: i32,
    pub sort_order: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attribute_attribute::Entity",
        from = "Column::AttributeId",
        to = "super::attribute_attribute::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AttributeAttribute,
    #[sea_orm(
        belongs_to = "super::product_producttype::Entity",
        from = "Column::ProductTypeId",
        to = "super::product_producttype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProducttype,
}

impl Related<super::attribute_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttribute.def()
    }
}

impl Related<super::product_producttype::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProducttype.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
