//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attribute_assignedpageattributevalue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sort_order: Option<i32>,
    pub value_id: i32,
    pub page_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attribute_attributevalue::Entity",
        from = "Column::ValueId",
        to = "super::attribute_attributevalue::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AttributeAttributevalue,
    #[sea_orm(
        belongs_to = "super::page_page::Entity",
        from = "Column::PageId",
        to = "super::page_page::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PagePage,
}

impl Related<super::attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevalue.def()
    }
}

impl Related<super::page_page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PagePage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
