//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attribute_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub input_type: String,
    pub available_in_grid: bool,
    pub visible_in_storefront: bool,
    pub filterable_in_dashboard: bool,
    pub filterable_in_storefront: bool,
    pub value_required: bool,
    pub storefront_search_position: i32,
    pub is_variant_only: bool,
    pub r#type: String,
    pub entity_type: Option<String>,
    pub unit: Option<String>,
    #[sea_orm(unique)]
    pub external_reference: Option<String>,
    pub max_sort_order: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_attribute_reference_page_types::Entity")]
    AttributeAttributeReferencePageTypes,
    #[sea_orm(has_many = "super::attribute_attribute_reference_product_types::Entity")]
    AttributeAttributeReferenceProductTypes,
    #[sea_orm(has_many = "super::attribute_attributecustomertype::Entity")]
    AttributeAttributecustomertype,
    #[sea_orm(has_many = "super::attribute_attributepage::Entity")]
    AttributeAttributepage,
    #[sea_orm(has_many = "super::attribute_attributeproduct::Entity")]
    AttributeAttributeproduct,
    #[sea_orm(has_many = "super::attribute_attributetranslation::Entity")]
    AttributeAttributetranslation,
    #[sea_orm(has_many = "super::attribute_attributevalue::Entity")]
    AttributeAttributevalue,
    #[sea_orm(has_many = "super::attribute_attributevariant::Entity")]
    AttributeAttributevariant,
}

impl Related<super::attribute_attribute_reference_page_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributeReferencePageTypes.def()
    }
}

impl Related<super::attribute_attribute_reference_product_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributeReferenceProductTypes.def()
    }
}

impl Related<super::attribute_attributecustomertype::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributecustomertype.def()
    }
}

impl Related<super::attribute_attributepage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributepage.def()
    }
}

impl Related<super::attribute_attributeproduct::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributeproduct.def()
    }
}

impl Related<super::attribute_attributetranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributetranslation.def()
    }
}

impl Related<super::attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevalue.def()
    }
}

impl Related<super::attribute_attributevariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevariant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
