//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "channel_channel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub is_active: bool,
    pub currency_code: String,
    pub default_country: String,
    pub allocation_strategy: String,
    pub automatically_confirm_all_new_orders: Option<bool>,
    pub automatically_fulfill_non_shippable_gift_card: Option<bool>,
    pub order_mark_as_paid_strategy: String,
    pub default_transaction_flow_strategy: String,
    pub expire_orders_after: Option<i32>,
    pub delete_expired_orders_after: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub allow_unpaid_orders: bool,
    pub use_legacy_error_flow_for_checkout: bool,
    pub include_draft_order_in_voucher_usage: bool,
    pub automatically_complete_fully_paid_checkouts: bool,
    pub draft_order_line_price_freeze_period: Option<i32>,
    pub use_legacy_line_discount_propagation_for_order: bool,
    pub checkout_release_funds_cut_off_date: Option<DateTimeWithTimeZone>,
    pub checkout_ttl_before_releasing_funds: String,
    pub release_funds_for_expired_checkouts: bool,
    pub automatic_completion_delay: Option<i32>,
    pub automatic_completion_cut_off_date: Option<DateTimeWithTimeZone>,
    pub allow_legacy_gift_card_use: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_group_channels::Entity")]
    AccountGroupChannels,
    #[sea_orm(has_many = "super::checkout_checkout::Entity")]
    CheckoutCheckout,
    #[sea_orm(has_many = "super::discount_promotionrule_channels::Entity")]
    DiscountPromotionruleChannels,
    #[sea_orm(has_many = "super::discount_voucherchannellisting::Entity")]
    DiscountVoucherchannellisting,
    #[sea_orm(has_many = "super::order_order::Entity")]
    OrderOrder,
    #[sea_orm(has_many = "super::plugins_pluginconfiguration::Entity")]
    PluginsPluginconfiguration,
    #[sea_orm(has_many = "super::product_collectionchannellisting::Entity")]
    ProductCollectionchannellisting,
    #[sea_orm(has_many = "super::product_productchannellisting::Entity")]
    ProductProductchannellisting,
    #[sea_orm(has_many = "super::product_productvariantchannellisting::Entity")]
    ProductProductvariantchannellisting,
    #[sea_orm(has_many = "super::shipping_shippingmethodchannellisting::Entity")]
    ShippingShippingmethodchannellisting,
    #[sea_orm(has_many = "super::shipping_shippingzone_channels::Entity")]
    ShippingShippingzoneChannels,
    #[sea_orm(has_one = "super::tax_taxconfiguration::Entity")]
    TaxTaxconfiguration,
    #[sea_orm(has_many = "super::warehouse_channelwarehouse::Entity")]
    WarehouseChannelwarehouse,
}

impl Related<super::account_group_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountGroupChannels.def()
    }
}

impl Related<super::checkout_checkout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckout.def()
    }
}

impl Related<super::discount_promotionrule_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionruleChannels.def()
    }
}

impl Related<super::discount_voucherchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherchannellisting.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl Related<super::plugins_pluginconfiguration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginsPluginconfiguration.def()
    }
}

impl Related<super::product_collectionchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollectionchannellisting.def()
    }
}

impl Related<super::product_productchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductchannellisting.def()
    }
}

impl Related<super::product_productvariantchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariantchannellisting.def()
    }
}

impl Related<super::shipping_shippingmethodchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingmethodchannellisting.def()
    }
}

impl Related<super::shipping_shippingzone_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingzoneChannels.def()
    }
}

impl Related<super::tax_taxconfiguration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxTaxconfiguration.def()
    }
}

impl Related<super::warehouse_channelwarehouse::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseChannelwarehouse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
