//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checkout_checkout_gift_cards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub checkout_id: Uuid,
    pub giftcard_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checkout_checkout::Entity",
        from = "Column::CheckoutId",
        to = "super::checkout_checkout::Column::Token",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CheckoutCheckout,
    #[sea_orm(
        belongs_to = "super::giftcard_giftcard::Entity",
        from = "Column::GiftcardId",
        to = "super::giftcard_giftcard::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GiftcardGiftcard,
}

impl Related<super::checkout_checkout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckout.def()
    }
}

impl Related<super::giftcard_giftcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcard.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
