//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checkout_checkoutdelivery")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub external_shipping_method_id: Option<String>,
    pub built_in_shipping_method_id: Option<i32>,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub price_amount: Decimal,
    pub currency: String,
    pub maximum_delivery_days: Option<i32>,
    pub minimum_delivery_days: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub active: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    pub is_external: bool,
    pub is_valid: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub tax_class_id: Option<i32>,
    pub tax_class_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub tax_class_private_metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub tax_class_metadata: Json,
    pub checkout_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checkout_checkout::Entity",
        from = "Column::CheckoutId",
        to = "super::checkout_checkout::Column::Token",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CheckoutCheckout,
}

impl Related<super::checkout_checkout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckout.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
