//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checkout_checkout")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub last_change: DateTimeWithTimeZone,
    pub email: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub token: Uuid,
    pub user_id: Option<i32>,
    pub billing_address_id: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub discount_amount: Decimal,
    pub discount_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub note: String,
    pub shipping_address_id: Option<i32>,
    pub shipping_method_id: Option<i32>,
    pub voucher_code: Option<String>,
    pub translated_discount_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub private_metadata: Option<Json>,
    pub currency: String,
    pub country: String,
    pub redirect_url: Option<String>,
    pub tracking_code: Option<String>,
    pub channel_id: i32,
    pub language_code: String,
    pub collection_point_id: Option<Uuid>,
    pub price_expiration: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub shipping_price_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub shipping_price_net_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))")]
    pub shipping_tax_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub subtotal_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub subtotal_net_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub total_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub total_net_amount: Decimal,
    pub tax_exemption: bool,
    pub authorize_status: String,
    pub charge_status: String,
    pub last_transaction_modified_at: Option<DateTimeWithTimeZone>,
    pub automatically_refundable: bool,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub base_subtotal_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub base_total_amount: Decimal,
    pub tax_error: Option<String>,
    pub is_voucher_usage_increased: bool,
    pub completing_started_at: Option<DateTimeWithTimeZone>,
    pub external_shipping_method_id: Option<String>,
    pub shipping_method_name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_base_shipping_price_amount: Decimal,
    pub save_billing_address: bool,
    pub save_shipping_address: bool,
    pub discount_expiration: DateTimeWithTimeZone,
    pub last_automatic_completion_attempt: Option<DateTimeWithTimeZone>,
    pub delivery_methods_stale_at: Option<DateTimeWithTimeZone>,
    pub assigned_delivery_id: Option<Uuid>,
    #[sea_orm(column_type = "custom(\"tsvector\")", nullable)]
    pub search_vector: Option<String>,
    pub search_index_dirty: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_address::Entity",
        from = "Column::BillingAddressId",
        to = "super::account_address::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountAddress2,
    #[sea_orm(
        belongs_to = "super::account_address::Entity",
        from = "Column::ShippingAddressId",
        to = "super::account_address::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountAddress1,
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(has_many = "super::checkout_checkout_gift_cards::Entity")]
    CheckoutCheckoutGiftCards,
    #[sea_orm(
        belongs_to = "super::checkout_checkoutdelivery::Entity",
        from = "Column::AssignedDeliveryId",
        to = "super::checkout_checkoutdelivery::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CheckoutCheckoutdelivery,
    #[sea_orm(has_many = "super::checkout_checkoutline::Entity")]
    CheckoutCheckoutline,
    #[sea_orm(has_one = "super::checkout_checkoutmetadata::Entity")]
    CheckoutCheckoutmetadata,
    #[sea_orm(has_many = "super::discount_checkoutdiscount::Entity")]
    DiscountCheckoutdiscount,
    #[sea_orm(has_many = "super::payment_payment::Entity")]
    PaymentPayment,
    #[sea_orm(has_many = "super::payment_transactionitem::Entity")]
    PaymentTransactionitem,
    #[sea_orm(
        belongs_to = "super::shipping_shippingmethod::Entity",
        from = "Column::ShippingMethodId",
        to = "super::shipping_shippingmethod::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingShippingmethod,
    #[sea_orm(
        belongs_to = "super::warehouse_warehouse::Entity",
        from = "Column::CollectionPointId",
        to = "super::warehouse_warehouse::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WarehouseWarehouse,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::checkout_checkout_gift_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckoutGiftCards.def()
    }
}

impl Related<super::checkout_checkoutdelivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckoutdelivery.def()
    }
}

impl Related<super::checkout_checkoutline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckoutline.def()
    }
}

impl Related<super::checkout_checkoutmetadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckoutmetadata.def()
    }
}

impl Related<super::discount_checkoutdiscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountCheckoutdiscount.def()
    }
}

impl Related<super::payment_payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentPayment.def()
    }
}

impl Related<super::payment_transactionitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactionitem.def()
    }
}

impl Related<super::shipping_shippingmethod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingmethod.def()
    }
}

impl Related<super::warehouse_warehouse::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseWarehouse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
