//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checkout_checkoutline")]
pub struct Model {
    pub quantity: i32,
    pub checkout_id: Uuid,
    pub variant_id: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))", nullable)]
    pub price_override: Option<Decimal>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub old_id: Option<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub currency: String,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))")]
    pub tax_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub total_price_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub total_price_net_amount: Decimal,
    pub is_gift: bool,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_unit_price_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))", nullable)]
    pub prior_unit_price_amount: Option<Decimal>,
    pub price_override_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checkout_checkout::Entity",
        from = "Column::CheckoutId",
        to = "super::checkout_checkout::Column::Token",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CheckoutCheckout,
    #[sea_orm(has_many = "super::discount_checkoutlinediscount::Entity")]
    DiscountCheckoutlinediscount,
    #[sea_orm(
        belongs_to = "super::product_productvariant::Entity",
        from = "Column::VariantId",
        to = "super::product_productvariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariant,
    #[sea_orm(has_many = "super::warehouse_preorderreservation::Entity")]
    WarehousePreorderreservation,
    #[sea_orm(has_many = "super::warehouse_reservation::Entity")]
    WarehouseReservation,
}

impl Related<super::checkout_checkout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckout.def()
    }
}

impl Related<super::discount_checkoutlinediscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountCheckoutlinediscount.def()
    }
}

impl Related<super::product_productvariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariant.def()
    }
}

impl Related<super::warehouse_preorderreservation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehousePreorderreservation.def()
    }
}

impl Related<super::warehouse_reservation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseReservation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
