//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "core_eventdeliveryattempt")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub task_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub duration: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_headers: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_headers: Option<String>,
    pub status: String,
    pub delivery_id: Option<i32>,
    pub response_status_code: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::core_eventdelivery::Entity",
        from = "Column::DeliveryId",
        to = "super::core_eventdelivery::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreEventdelivery,
}

impl Related<super::core_eventdelivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreEventdelivery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
