//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "core_eventpayload")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub created_at: DateTimeWithTimeZone,
    pub payload_file: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::core_eventdelivery::Entity")]
    CoreEventdelivery,
}

impl Related<super::core_eventdelivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreEventdelivery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
