//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "csv_exportevent")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTimeWithTimeZone,
    pub r#type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub parameters: Json,
    pub app_id: Option<i32>,
    pub export_file_id: i32,
    pub user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
    #[sea_orm(
        belongs_to = "super::app_app::Entity",
        from = "Column::AppId",
        to = "super::app_app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppApp,
    #[sea_orm(
        belongs_to = "super::csv_exportfile::Entity",
        from = "Column::ExportFileId",
        to = "super::csv_exportfile::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CsvExportfile,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl Related<super::app_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApp.def()
    }
}

impl Related<super::csv_exportfile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CsvExportfile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
