//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "csv_exportfile")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub content_file: Option<String>,
    pub app_id: Option<i32>,
    pub user_id: Option<i32>,
    pub message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
    #[sea_orm(
        belongs_to = "super::app_app::Entity",
        from = "Column::AppId",
        to = "super::app_app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppApp,
    #[sea_orm(has_many = "super::csv_exportevent::Entity")]
    CsvExportevent,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl Related<super::app_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApp.def()
    }
}

impl Related<super::csv_exportevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CsvExportevent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
