//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_vouchercustomer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub customer_email: String,
    pub voucher_code_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discount_vouchercode::Entity",
        from = "Column::VoucherCodeId",
        to = "super::discount_vouchercode::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountVouchercode,
}

impl Related<super::discount_vouchercode::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVouchercode.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
