//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_voucher")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#type: String,
    pub name: Option<String>,
    pub usage_limit: Option<i32>,
    pub start_date: DateTimeWithTimeZone,
    pub end_date: Option<DateTimeWithTimeZone>,
    pub discount_value_type: String,
    pub apply_once_per_order: bool,
    pub countries: String,
    pub min_checkout_items_quantity: Option<i32>,
    pub apply_once_per_customer: bool,
    pub only_for_staff: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub single_use: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discount_checkoutdiscount::Entity")]
    DiscountCheckoutdiscount,
    #[sea_orm(has_many = "super::discount_checkoutlinediscount::Entity")]
    DiscountCheckoutlinediscount,
    #[sea_orm(has_many = "super::discount_orderdiscount::Entity")]
    DiscountOrderdiscount,
    #[sea_orm(has_many = "super::discount_orderlinediscount::Entity")]
    DiscountOrderlinediscount,
    #[sea_orm(has_many = "super::discount_voucher_categories::Entity")]
    DiscountVoucherCategories,
    #[sea_orm(has_many = "super::discount_voucher_collections::Entity")]
    DiscountVoucherCollections,
    #[sea_orm(has_many = "super::discount_voucher_products::Entity")]
    DiscountVoucherProducts,
    #[sea_orm(has_many = "super::discount_voucher_variants::Entity")]
    DiscountVoucherVariants,
    #[sea_orm(has_many = "super::discount_voucherchannellisting::Entity")]
    DiscountVoucherchannellisting,
    #[sea_orm(has_many = "super::discount_vouchercode::Entity")]
    DiscountVouchercode,
    #[sea_orm(has_many = "super::discount_vouchertranslation::Entity")]
    DiscountVouchertranslation,
    #[sea_orm(has_many = "super::order_order::Entity")]
    OrderOrder,
}

impl Related<super::discount_checkoutdiscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountCheckoutdiscount.def()
    }
}

impl Related<super::discount_checkoutlinediscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountCheckoutlinediscount.def()
    }
}

impl Related<super::discount_orderdiscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountOrderdiscount.def()
    }
}

impl Related<super::discount_orderlinediscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountOrderlinediscount.def()
    }
}

impl Related<super::discount_voucher_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherCategories.def()
    }
}

impl Related<super::discount_voucher_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherCollections.def()
    }
}

impl Related<super::discount_voucher_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherProducts.def()
    }
}

impl Related<super::discount_voucher_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherVariants.def()
    }
}

impl Related<super::discount_voucherchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherchannellisting.def()
    }
}

impl Related<super::discount_vouchercode::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVouchercode.def()
    }
}

impl Related<super::discount_vouchertranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVouchertranslation.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
