//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_promotionrule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    pub catalogue_predicate: Json,
    pub reward_value_type: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))", nullable)]
    pub reward_value: Option<Decimal>,
    pub promotion_id: Uuid,
    #[sea_orm(unique)]
    pub old_channel_listing_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub order_predicate: Json,
    pub reward_type: Option<String>,
    pub variants_dirty: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discount_checkoutdiscount::Entity")]
    DiscountCheckoutdiscount,
    #[sea_orm(has_many = "super::discount_checkoutlinediscount::Entity")]
    DiscountCheckoutlinediscount,
    #[sea_orm(has_many = "super::discount_orderdiscount::Entity")]
    DiscountOrderdiscount,
    #[sea_orm(has_many = "super::discount_orderlinediscount::Entity")]
    DiscountOrderlinediscount,
    #[sea_orm(
        belongs_to = "super::discount_promotion::Entity",
        from = "Column::PromotionId",
        to = "super::discount_promotion::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountPromotion,
    #[sea_orm(has_many = "super::discount_promotionrule_channels::Entity")]
    DiscountPromotionruleChannels,
    #[sea_orm(has_many = "super::discount_promotionrule_gifts::Entity")]
    DiscountPromotionruleGifts,
    #[sea_orm(has_many = "super::discount_promotionrule_variants::Entity")]
    DiscountPromotionruleVariants,
    #[sea_orm(has_many = "super::discount_promotionruletranslation::Entity")]
    DiscountPromotionruletranslation,
    #[sea_orm(has_many = "super::product_variantchannellistingpromotionrule::Entity")]
    ProductVariantchannellistingpromotionrule,
}

impl Related<super::discount_checkoutdiscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountCheckoutdiscount.def()
    }
}

impl Related<super::discount_checkoutlinediscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountCheckoutlinediscount.def()
    }
}

impl Related<super::discount_orderdiscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountOrderdiscount.def()
    }
}

impl Related<super::discount_orderlinediscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountOrderlinediscount.def()
    }
}

impl Related<super::discount_promotion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotion.def()
    }
}

impl Related<super::discount_promotionrule_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionruleChannels.def()
    }
}

impl Related<super::discount_promotionrule_gifts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionruleGifts.def()
    }
}

impl Related<super::discount_promotionrule_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionruleVariants.def()
    }
}

impl Related<super::discount_promotionruletranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionruletranslation.def()
    }
}

impl Related<super::product_variantchannellistingpromotionrule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariantchannellistingpromotionrule.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
