//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_promotionevent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub date: DateTimeWithTimeZone,
    pub r#type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub parameters: Json,
    pub app_id: Option<i32>,
    pub promotion_id: Uuid,
    pub user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
    #[sea_orm(
        belongs_to = "super::app_app::Entity",
        from = "Column::AppId",
        to = "super::app_app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppApp,
    #[sea_orm(
        belongs_to = "super::discount_promotion::Entity",
        from = "Column::PromotionId",
        to = "super::discount_promotion::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountPromotion,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl Related<super::app_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApp.def()
    }
}

impl Related<super::discount_promotion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
