//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_checkoutlinediscount")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub r#type: String,
    pub value_type: String,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub value: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub amount_value: Decimal,
    pub currency: String,
    pub name: Option<String>,
    pub translated_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub line_id: Option<Uuid>,
    pub sale_id: Option<i32>,
    pub voucher_id: Option<i32>,
    pub promotion_rule_id: Option<Uuid>,
    pub voucher_code: Option<String>,
    pub unique_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checkout_checkoutline::Entity",
        from = "Column::LineId",
        to = "super::checkout_checkoutline::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CheckoutCheckoutline,
    #[sea_orm(
        belongs_to = "super::discount_promotionrule::Entity",
        from = "Column::PromotionRuleId",
        to = "super::discount_promotionrule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountPromotionrule,
    #[sea_orm(
        belongs_to = "super::discount_voucher::Entity",
        from = "Column::VoucherId",
        to = "super::discount_voucher::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountVoucher,
}

impl Related<super::checkout_checkoutline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckoutline.def()
    }
}

impl Related<super::discount_promotionrule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionrule.def()
    }
}

impl Related<super::discount_voucher::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucher.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
