//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_promotiontranslation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub language_code: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description: Option<Json>,
    pub promotion_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discount_promotion::Entity",
        from = "Column::PromotionId",
        to = "super::discount_promotion::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountPromotion,
}

impl Related<super::discount_promotion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
