//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_promotionrule_channels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub promotionrule_id: Uuid,
    pub channel_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(
        belongs_to = "super::discount_promotionrule::Entity",
        from = "Column::PromotionruleId",
        to = "super::discount_promotionrule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountPromotionrule,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::discount_promotionrule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionrule.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
