//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discount_voucher_collections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub voucher_id: i32,
    pub collection_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discount_voucher::Entity",
        from = "Column::VoucherId",
        to = "super::discount_voucher::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountVoucher,
    #[sea_orm(
        belongs_to = "super::product_collection::Entity",
        from = "Column::CollectionId",
        to = "super::product_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCollection,
}

impl Related<super::discount_voucher::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucher.def()
    }
}

impl Related<super::product_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
