//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_site")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub domain: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::site_sitesettings::Entity")]
    SiteSitesettings,
}

impl Related<super::site_sitesettings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteSitesettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
