//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_celery_beat_crontabschedule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub minute: String,
    pub hour: String,
    pub day_of_week: String,
    pub day_of_month: String,
    pub month_of_year: String,
    pub timezone: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::django_celery_beat_periodictask::Entity")]
    DjangoCeleryBeatPeriodictask,
}

impl Related<super::django_celery_beat_periodictask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatPeriodictask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
