//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_content_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub app_label: String,
    pub model: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::permission_permission::Entity")]
    PermissionPermission,
}

impl Related<super::permission_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermissionPermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
