//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_celery_beat_solarschedule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event: String,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub latitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub longitude: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::django_celery_beat_periodictask::Entity")]
    DjangoCeleryBeatPeriodictask,
}

impl Related<super::django_celery_beat_periodictask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatPeriodictask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
