//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_celery_beat_periodictask")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub task: String,
    #[sea_orm(column_type = "Text")]
    pub args: String,
    #[sea_orm(column_type = "Text")]
    pub kwargs: String,
    pub queue: Option<String>,
    pub exchange: Option<String>,
    pub routing_key: Option<String>,
    pub expires: Option<DateTimeWithTimeZone>,
    pub enabled: bool,
    pub last_run_at: Option<DateTimeWithTimeZone>,
    pub total_run_count: i32,
    pub date_changed: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub crontab_id: Option<i32>,
    pub interval_id: Option<i32>,
    pub solar_id: Option<i32>,
    pub one_off: bool,
    pub start_time: Option<DateTimeWithTimeZone>,
    pub priority: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub headers: String,
    pub clocked_id: Option<i32>,
    pub expire_seconds: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::django_celery_beat_clockedschedule::Entity",
        from = "Column::ClockedId",
        to = "super::django_celery_beat_clockedschedule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DjangoCeleryBeatClockedschedule,
    #[sea_orm(
        belongs_to = "super::django_celery_beat_crontabschedule::Entity",
        from = "Column::CrontabId",
        to = "super::django_celery_beat_crontabschedule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DjangoCeleryBeatCrontabschedule,
    #[sea_orm(
        belongs_to = "super::django_celery_beat_intervalschedule::Entity",
        from = "Column::IntervalId",
        to = "super::django_celery_beat_intervalschedule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DjangoCeleryBeatIntervalschedule,
    #[sea_orm(
        belongs_to = "super::django_celery_beat_solarschedule::Entity",
        from = "Column::SolarId",
        to = "super::django_celery_beat_solarschedule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DjangoCeleryBeatSolarschedule,
    #[sea_orm(has_one = "super::schedulers_customperiodictask::Entity")]
    SchedulersCustomperiodictask,
}

impl Related<super::django_celery_beat_clockedschedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatClockedschedule.def()
    }
}

impl Related<super::django_celery_beat_crontabschedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatCrontabschedule.def()
    }
}

impl Related<super::django_celery_beat_intervalschedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatIntervalschedule.def()
    }
}

impl Related<super::django_celery_beat_solarschedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatSolarschedule.def()
    }
}

impl Related<super::schedulers_customperiodictask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchedulersCustomperiodictask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
