//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "giftcard_giftcard_tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub giftcard_id: i32,
    pub giftcardtag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::giftcard_giftcard::Entity",
        from = "Column::GiftcardId",
        to = "super::giftcard_giftcard::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GiftcardGiftcard,
    #[sea_orm(
        belongs_to = "super::giftcard_giftcardtag::Entity",
        from = "Column::GiftcardtagId",
        to = "super::giftcard_giftcardtag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GiftcardGiftcardtag,
}

impl Related<super::giftcard_giftcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcard.def()
    }
}

impl Related<super::giftcard_giftcardtag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcardtag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
