//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "giftcard_giftcardevent")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTimeWithTimeZone,
    pub r#type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub parameters: Json,
    pub app_id: Option<i32>,
    pub gift_card_id: i32,
    pub user_id: Option<i32>,
    pub order_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
    #[sea_orm(
        belongs_to = "super::app_app::Entity",
        from = "Column::AppId",
        to = "super::app_app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppApp,
    #[sea_orm(
        belongs_to = "super::giftcard_giftcard::Entity",
        from = "Column::GiftCardId",
        to = "super::giftcard_giftcard::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GiftcardGiftcard,
    #[sea_orm(
        belongs_to = "super::order_order::Entity",
        from = "Column::OrderId",
        to = "super::order_order::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderOrder,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl Related<super::app_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApp.def()
    }
}

impl Related<super::giftcard_giftcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcard.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
