//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "giftcard_giftcardtag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::giftcard_giftcard_tags::Entity")]
    GiftcardGiftcardTags,
}

impl Related<super::giftcard_giftcard_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcardTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
