//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "invoice_invoice")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub number: Option<String>,
    pub created: Option<DateTimeWithTimeZone>,
    pub external_url: Option<String>,
    pub invoice_file: String,
    pub message: Option<String>,
    pub order_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::invoice_invoiceevent::Entity")]
    InvoiceInvoiceevent,
    #[sea_orm(
        belongs_to = "super::order_order::Entity",
        from = "Column::OrderId",
        to = "super::order_order::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderOrder,
}

impl Related<super::invoice_invoiceevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvoiceInvoiceevent.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
