//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "menu_menuitemtranslation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub language_code: String,
    pub name: String,
    pub menu_item_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::menu_menuitem::Entity",
        from = "Column::MenuItemId",
        to = "super::menu_menuitem::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MenuMenuitem,
}

impl Related<super::menu_menuitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuMenuitem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
