//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "menu_menuitem")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub sort_order: Option<i32>,
    pub url: Option<String>,
    pub lft: i32,
    pub rght: i32,
    pub tree_id: i32,
    pub level: i32,
    pub category_id: Option<i32>,
    pub collection_id: Option<i32>,
    pub menu_id: i32,
    pub page_id: Option<i32>,
    pub parent_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::menu_menu::Entity",
        from = "Column::MenuId",
        to = "super::menu_menu::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MenuMenu,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::menu_menuitemtranslation::Entity")]
    MenuMenuitemtranslation,
    #[sea_orm(
        belongs_to = "super::page_page::Entity",
        from = "Column::PageId",
        to = "super::page_page::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PagePage,
    #[sea_orm(
        belongs_to = "super::product_category::Entity",
        from = "Column::CategoryId",
        to = "super::product_category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCategory,
    #[sea_orm(
        belongs_to = "super::product_collection::Entity",
        from = "Column::CollectionId",
        to = "super::product_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCollection,
}

impl Related<super::menu_menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuMenu.def()
    }
}

impl Related<super::menu_menuitemtranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuMenuitemtranslation.def()
    }
}

impl Related<super::page_page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PagePage.def()
    }
}

impl Related<super::product_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategory.def()
    }
}

impl Related<super::product_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
