//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order_orderline")]
pub struct Model {
    pub product_name: String,
    pub product_sku: Option<String>,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub unit_price_net_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub unit_price_gross_amount: Decimal,
    pub is_shipping_required: bool,
    pub quantity_fulfilled: i32,
    pub variant_id: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 4)))", nullable)]
    pub tax_rate: Option<Decimal>,
    pub translated_product_name: String,
    pub currency: String,
    pub translated_variant_name: String,
    pub variant_name: String,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub total_price_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub total_price_net_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub unit_discount_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub unit_discount_value: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub unit_discount_reason: Option<String>,
    pub unit_discount_type: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_total_price_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_total_price_net_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_unit_price_gross_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_unit_price_net_amount: Decimal,
    pub is_gift_card: bool,
    pub product_variant_id: Option<String>,
    pub sale_id: Option<String>,
    pub voucher_code: Option<String>,
    pub order_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub old_id: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub base_unit_price_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub undiscounted_base_unit_price_amount: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub tax_class_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub tax_class_metadata: Json,
    pub tax_class_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub tax_class_private_metadata: Json,
    pub is_gift: bool,
    pub is_price_overridden: Option<bool>,
    pub draft_base_price_expire_at: Option<DateTimeWithTimeZone>,
    pub product_type_id: Option<i32>,
    pub price_override_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discount_orderlinediscount::Entity")]
    DiscountOrderlinediscount,
    #[sea_orm(has_many = "super::order_fulfillmentline::Entity")]
    OrderFulfillmentline,
    #[sea_orm(
        belongs_to = "super::order_order::Entity",
        from = "Column::OrderId",
        to = "super::order_order::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderOrder,
    #[sea_orm(has_many = "super::order_ordergrantedrefundline::Entity")]
    OrderOrdergrantedrefundline,
    #[sea_orm(
        belongs_to = "super::product_productvariant::Entity",
        from = "Column::VariantId",
        to = "super::product_productvariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariant,
    #[sea_orm(
        belongs_to = "super::tax_taxclass::Entity",
        from = "Column::TaxClassId",
        to = "super::tax_taxclass::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaxTaxclass,
    #[sea_orm(has_many = "super::warehouse_allocation::Entity")]
    WarehouseAllocation,
    #[sea_orm(has_many = "super::warehouse_preorderallocation::Entity")]
    WarehousePreorderallocation,
}

impl Related<super::discount_orderlinediscount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountOrderlinediscount.def()
    }
}

impl Related<super::order_fulfillmentline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderFulfillmentline.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl Related<super::order_ordergrantedrefundline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrdergrantedrefundline.def()
    }
}

impl Related<super::product_productvariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariant.def()
    }
}

impl Related<super::tax_taxclass::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxTaxclass.def()
    }
}

impl Related<super::warehouse_allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseAllocation.def()
    }
}

impl Related<super::warehouse_preorderallocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehousePreorderallocation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
