//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order_ordergrantedrefundline")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub quantity: i32,
    pub granted_refund_id: i32,
    pub order_line_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub reason_reference_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::order_ordergrantedrefund::Entity",
        from = "Column::GrantedRefundId",
        to = "super::order_ordergrantedrefund::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderOrdergrantedrefund,
    #[sea_orm(
        belongs_to = "super::order_orderline::Entity",
        from = "Column::OrderLineId",
        to = "super::order_orderline::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderOrderline,
    #[sea_orm(
        belongs_to = "super::page_page::Entity",
        from = "Column::ReasonReferenceId",
        to = "super::page_page::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PagePage,
}

impl Related<super::order_ordergrantedrefund::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrdergrantedrefund.def()
    }
}

impl Related<super::order_orderline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrderline.def()
    }
}

impl Related<super::page_page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PagePage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
