//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "page_page")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub title: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub content: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub is_published: bool,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub seo_description: Option<String>,
    pub seo_title: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub page_type_id: i32,
    pub search_index_dirty: bool,
    #[sea_orm(column_type = "custom(\"tsvector\")", nullable)]
    pub search_vector: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_assignedpageattributevalue::Entity")]
    AttributeAssignedpageattributevalue,
    #[sea_orm(has_many = "super::attribute_attributevalue::Entity")]
    AttributeAttributevalue,
    #[sea_orm(has_many = "super::menu_menuitem::Entity")]
    MenuMenuitem,
    #[sea_orm(has_many = "super::order_fulfillment::Entity")]
    OrderFulfillment,
    #[sea_orm(has_many = "super::order_fulfillmentline::Entity")]
    OrderFulfillmentline,
    #[sea_orm(has_many = "super::order_ordergrantedrefund::Entity")]
    OrderOrdergrantedrefund,
    #[sea_orm(has_many = "super::order_ordergrantedrefundline::Entity")]
    OrderOrdergrantedrefundline,
    #[sea_orm(has_many = "super::page_pagetranslation::Entity")]
    PagePagetranslation,
    #[sea_orm(
        belongs_to = "super::page_pagetype::Entity",
        from = "Column::PageTypeId",
        to = "super::page_pagetype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PagePagetype,
    #[sea_orm(has_many = "super::payment_transactionevent::Entity")]
    PaymentTransactionevent,
}

impl Related<super::attribute_assignedpageattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssignedpageattributevalue.def()
    }
}

impl Related<super::attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevalue.def()
    }
}

impl Related<super::menu_menuitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuMenuitem.def()
    }
}

impl Related<super::order_fulfillment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderFulfillment.def()
    }
}

impl Related<super::order_fulfillmentline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderFulfillmentline.def()
    }
}

impl Related<super::order_ordergrantedrefund::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrdergrantedrefund.def()
    }
}

impl Related<super::order_ordergrantedrefundline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrdergrantedrefundline.def()
    }
}

impl Related<super::page_pagetranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PagePagetranslation.def()
    }
}

impl Related<super::page_pagetype::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PagePagetype.def()
    }
}

impl Related<super::payment_transactionevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactionevent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
