//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "payment_transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub token: String,
    pub kind: String,
    pub is_success: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub currency: String,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub gateway_response: Json,
    pub payment_id: i32,
    pub customer_id: Option<String>,
    pub action_required: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub action_required_data: Json,
    pub already_processed: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub legacy_adyen_plugin_payment_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub legacy_adyen_plugin_result_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_payment::Entity",
        from = "Column::PaymentId",
        to = "super::payment_payment::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PaymentPayment,
}

impl Related<super::payment_payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentPayment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
