//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plugins_pluginconfiguration")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub active: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub configuration: Json,
    pub identifier: String,
    pub channel_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(has_many = "super::plugins_emailtemplate::Entity")]
    PluginsEmailtemplate,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::plugins_emailtemplate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginsEmailtemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
