//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_producttranslation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub seo_title: Option<String>,
    pub seo_description: Option<String>,
    pub language_code: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description: Option<Json>,
    pub product_id: i32,
    pub slug: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_product::Entity",
        from = "Column::ProductId",
        to = "super::product_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProduct,
}

impl Related<super::product_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
