//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "product_product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description: Option<Json>,
    pub updated_at: DateTimeWithTimeZone,
    pub product_type_id: i32,
    pub category_id: Option<i32>,
    pub seo_description: Option<String>,
    pub seo_title: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight: Option<f64>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(unique)]
    pub default_variant_id: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub description_plaintext: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub rating: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub search_document: String,
    pub created_at: DateTimeWithTimeZone,
    pub search_index_dirty: bool,
    pub tax_class_id: Option<i32>,
    #[sea_orm(unique)]
    pub external_reference: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_assignedproductattributevalue::Entity")]
    AttributeAssignedproductattributevalue,
    #[sea_orm(has_many = "super::attribute_attributevalue::Entity")]
    AttributeAttributevalue,
    #[sea_orm(has_many = "super::discount_voucher_products::Entity")]
    DiscountVoucherProducts,
    #[sea_orm(has_many = "super::giftcard_giftcard::Entity")]
    GiftcardGiftcard,
    #[sea_orm(
        belongs_to = "super::product_category::Entity",
        from = "Column::CategoryId",
        to = "super::product_category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCategory,
    #[sea_orm(has_many = "super::product_collectionproduct::Entity")]
    ProductCollectionproduct,
    #[sea_orm(has_many = "super::product_productchannellisting::Entity")]
    ProductProductchannellisting,
    #[sea_orm(has_many = "super::product_productmedia::Entity")]
    ProductProductmedia,
    #[sea_orm(has_many = "super::product_producttranslation::Entity")]
    ProductProducttranslation,
    #[sea_orm(
        belongs_to = "super::product_producttype::Entity",
        from = "Column::ProductTypeId",
        to = "super::product_producttype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProducttype,
    #[sea_orm(
        belongs_to = "super::product_productvariant::Entity",
        from = "Column::DefaultVariantId",
        to = "super::product_productvariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariant,
    #[sea_orm(has_many = "super::shipping_shippingmethod_excluded_products::Entity")]
    ShippingShippingmethodExcludedProducts,
    #[sea_orm(
        belongs_to = "super::tax_taxclass::Entity",
        from = "Column::TaxClassId",
        to = "super::tax_taxclass::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaxTaxclass,
}

impl Related<super::attribute_assignedproductattributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAssignedproductattributevalue.def()
    }
}

impl Related<super::attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevalue.def()
    }
}

impl Related<super::discount_voucher_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherProducts.def()
    }
}

impl Related<super::giftcard_giftcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcardGiftcard.def()
    }
}

impl Related<super::product_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategory.def()
    }
}

impl Related<super::product_collectionproduct::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollectionproduct.def()
    }
}

impl Related<super::product_productchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductchannellisting.def()
    }
}

impl Related<super::product_productmedia::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductmedia.def()
    }
}

impl Related<super::product_producttranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProducttranslation.def()
    }
}

impl Related<super::product_producttype::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProducttype.def()
    }
}

impl Related<super::product_productvariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariant.def()
    }
}

impl Related<super::shipping_shippingmethod_excluded_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingmethodExcludedProducts.def()
    }
}

impl Related<super::tax_taxclass::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxTaxclass.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
