//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_collection")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub background_image: Option<String>,
    pub seo_description: Option<String>,
    pub seo_title: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description: Option<Json>,
    pub background_image_alt: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_attributevalue::Entity")]
    AttributeAttributevalue,
    #[sea_orm(has_many = "super::discount_voucher_collections::Entity")]
    DiscountVoucherCollections,
    #[sea_orm(has_many = "super::menu_menuitem::Entity")]
    MenuMenuitem,
    #[sea_orm(has_many = "super::product_collectionchannellisting::Entity")]
    ProductCollectionchannellisting,
    #[sea_orm(has_many = "super::product_collectionproduct::Entity")]
    ProductCollectionproduct,
    #[sea_orm(has_many = "super::product_collectiontranslation::Entity")]
    ProductCollectiontranslation,
    #[sea_orm(has_many = "super::thumbnail_thumbnail::Entity")]
    ThumbnailThumbnail,
}

impl Related<super::attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevalue.def()
    }
}

impl Related<super::discount_voucher_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountVoucherCollections.def()
    }
}

impl Related<super::menu_menuitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuMenuitem.def()
    }
}

impl Related<super::product_collectionchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollectionchannellisting.def()
    }
}

impl Related<super::product_collectionproduct::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollectionproduct.def()
    }
}

impl Related<super::product_collectiontranslation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollectiontranslation.def()
    }
}

impl Related<super::thumbnail_thumbnail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThumbnailThumbnail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
