//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_productvarianttranslation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub language_code: String,
    pub name: String,
    pub product_variant_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_productvariant::Entity",
        from = "Column::ProductVariantId",
        to = "super::product_productvariant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariant,
}

impl Related<super::product_productvariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
