//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_collectionchannellisting")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub is_published: bool,
    pub channel_id: i32,
    pub collection_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(
        belongs_to = "super::product_collection::Entity",
        from = "Column::CollectionId",
        to = "super::product_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCollection,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::product_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
