//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "product_producttype")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub has_variants: bool,
    pub is_shipping_required: bool,
    #[sea_orm(column_type = "Double")]
    pub weight: f64,
    pub is_digital: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    #[sea_orm(unique)]
    pub slug: String,
    pub kind: String,
    pub tax_class_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_attribute_reference_product_types::Entity")]
    AttributeAttributeReferenceProductTypes,
    #[sea_orm(has_many = "super::attribute_attributeproduct::Entity")]
    AttributeAttributeproduct,
    #[sea_orm(has_many = "super::attribute_attributevariant::Entity")]
    AttributeAttributevariant,
    #[sea_orm(has_many = "super::product_product::Entity")]
    ProductProduct,
    #[sea_orm(
        belongs_to = "super::tax_taxclass::Entity",
        from = "Column::TaxClassId",
        to = "super::tax_taxclass::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaxTaxclass,
}

impl Related<super::attribute_attribute_reference_product_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributeReferenceProductTypes.def()
    }
}

impl Related<super::attribute_attributeproduct::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributeproduct.def()
    }
}

impl Related<super::attribute_attributevariant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeAttributevariant.def()
    }
}

impl Related<super::product_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProduct.def()
    }
}

impl Related<super::tax_taxclass::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxTaxclass.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
