//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_productchannellisting")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub is_published: bool,
    pub channel_id: i32,
    pub product_id: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))", nullable)]
    pub discounted_price_amount: Option<Decimal>,
    pub currency: String,
    pub visible_in_listings: bool,
    pub available_for_purchase_at: Option<DateTimeWithTimeZone>,
    pub discounted_price_dirty: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(
        belongs_to = "super::product_product::Entity",
        from = "Column::ProductId",
        to = "super::product_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProduct,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::product_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
