//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_variantchannellistingpromotionrule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub discount_amount: Decimal,
    pub currency: String,
    pub promotion_rule_id: Uuid,
    pub variant_channel_listing_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discount_promotionrule::Entity",
        from = "Column::PromotionRuleId",
        to = "super::discount_promotionrule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DiscountPromotionrule,
    #[sea_orm(
        belongs_to = "super::product_productvariantchannellisting::Entity",
        from = "Column::VariantChannelListingId",
        to = "super::product_productvariantchannellisting::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductvariantchannellisting,
}

impl Related<super::discount_promotionrule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountPromotionrule.def()
    }
}

impl Related<super::product_productvariantchannellisting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductvariantchannellisting.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
