//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_productmedia")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sort_order: Option<i32>,
    pub image: Option<String>,
    pub alt: String,
    pub r#type: String,
    pub external_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub oembed_data: Json,
    pub product_id: Option<i32>,
    pub to_remove: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_product::Entity",
        from = "Column::ProductId",
        to = "super::product_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProduct,
    #[sea_orm(has_many = "super::product_variantmedia::Entity")]
    ProductVariantmedia,
    #[sea_orm(has_many = "super::thumbnail_thumbnail::Entity")]
    ThumbnailThumbnail,
}

impl Related<super::product_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProduct.def()
    }
}

impl Related<super::product_variantmedia::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariantmedia.def()
    }
}

impl Related<super::thumbnail_thumbnail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThumbnailThumbnail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
