//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "schedulers_customperiodictask")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub periodictask_ptr_id: i32,
    pub custom_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::django_celery_beat_periodictask::Entity",
        from = "Column::PeriodictaskPtrId",
        to = "super::django_celery_beat_periodictask::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DjangoCeleryBeatPeriodictask,
    #[sea_orm(
        belongs_to = "super::schedulers_customschedule::Entity",
        from = "Column::CustomId",
        to = "super::schedulers_customschedule::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SchedulersCustomschedule,
}

impl Related<super::django_celery_beat_periodictask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoCeleryBeatPeriodictask.def()
    }
}

impl Related<super::schedulers_customschedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchedulersCustomschedule.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
