//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "schedulers_customschedule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub schedule_import_path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::schedulers_customperiodictask::Entity")]
    SchedulersCustomperiodictask,
}

impl Related<super::schedulers_customperiodictask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SchedulersCustomperiodictask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
