//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shipping_shippingmethodpostalcoderule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub start: String,
    pub end: Option<String>,
    pub shipping_method_id: i32,
    pub inclusion_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::shipping_shippingmethod::Entity",
        from = "Column::ShippingMethodId",
        to = "super::shipping_shippingmethod::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingShippingmethod,
}

impl Related<super::shipping_shippingmethod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingmethod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
