//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shipping_shippingzone_channels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub shippingzone_id: i32,
    pub channel_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(
        belongs_to = "super::shipping_shippingzone::Entity",
        from = "Column::ShippingzoneId",
        to = "super::shipping_shippingzone::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingShippingzone,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::shipping_shippingzone::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingzone.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
