//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shipping_shippingmethodchannellisting")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))", nullable)]
    pub minimum_order_price_amount: Option<Decimal>,
    pub currency: String,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))", nullable)]
    pub maximum_order_price_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 3)))")]
    pub price_amount: Decimal,
    pub channel_id: i32,
    pub shipping_method_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(
        belongs_to = "super::shipping_shippingmethod::Entity",
        from = "Column::ShippingMethodId",
        to = "super::shipping_shippingmethod::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingShippingmethod,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::shipping_shippingmethod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingmethod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
