//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shipping_shippingmethod_excluded_products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub shippingmethod_id: i32,
    pub product_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_product::Entity",
        from = "Column::ProductId",
        to = "super::product_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProduct,
    #[sea_orm(
        belongs_to = "super::shipping_shippingmethod::Entity",
        from = "Column::ShippingmethodId",
        to = "super::shipping_shippingmethod::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingShippingmethod,
}

impl Related<super::product_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProduct.def()
    }
}

impl Related<super::shipping_shippingmethod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingShippingmethod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
