//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "site_sitesettingstranslation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub language_code: String,
    pub header_text: String,
    pub description: String,
    pub site_settings_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::site_sitesettings::Entity",
        from = "Column::SiteSettingsId",
        to = "super::site_sitesettings::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SiteSitesettings,
}

impl Related<super::site_sitesettings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteSitesettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
