//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tax_taxconfigurationpercountry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub country: String,
    pub charge_taxes: bool,
    pub tax_calculation_strategy: Option<String>,
    pub display_gross_prices: bool,
    pub tax_configuration_id: i32,
    pub tax_app_id: Option<String>,
    pub use_weighted_tax_for_shipping: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tax_taxconfiguration::Entity",
        from = "Column::TaxConfigurationId",
        to = "super::tax_taxconfiguration::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaxTaxconfiguration,
}

impl Related<super::tax_taxconfiguration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxTaxconfiguration.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
