//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "thumbnail_thumbnail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub image: String,
    pub size: i32,
    pub format: Option<String>,
    pub category_id: Option<i32>,
    pub collection_id: Option<i32>,
    pub product_media_id: Option<i32>,
    pub user_id: Option<i32>,
    pub app_id: Option<i32>,
    pub app_installation_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_user::Entity",
        from = "Column::UserId",
        to = "super::account_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountUser,
    #[sea_orm(
        belongs_to = "super::app_app::Entity",
        from = "Column::AppId",
        to = "super::app_app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppApp,
    #[sea_orm(
        belongs_to = "super::app_appinstallation::Entity",
        from = "Column::AppInstallationId",
        to = "super::app_appinstallation::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppAppinstallation,
    #[sea_orm(
        belongs_to = "super::product_category::Entity",
        from = "Column::CategoryId",
        to = "super::product_category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCategory,
    #[sea_orm(
        belongs_to = "super::product_collection::Entity",
        from = "Column::CollectionId",
        to = "super::product_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCollection,
    #[sea_orm(
        belongs_to = "super::product_productmedia::Entity",
        from = "Column::ProductMediaId",
        to = "super::product_productmedia::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductProductmedia,
}

impl Related<super::account_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountUser.def()
    }
}

impl Related<super::app_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApp.def()
    }
}

impl Related<super::app_appinstallation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppAppinstallation.def()
    }
}

impl Related<super::product_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategory.def()
    }
}

impl Related<super::product_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCollection.def()
    }
}

impl Related<super::product_productmedia::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductProductmedia.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
