//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "warehouse_warehouse")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub email: String,
    pub address_id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub private_metadata: Json,
    pub click_and_collect_option: String,
    pub is_private: bool,
    #[sea_orm(unique)]
    pub external_reference: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_address::Entity",
        from = "Column::AddressId",
        to = "super::account_address::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountAddress,
    #[sea_orm(has_many = "super::checkout_checkout::Entity")]
    CheckoutCheckout,
    #[sea_orm(has_many = "super::order_order::Entity")]
    OrderOrder,
    #[sea_orm(has_many = "super::warehouse_channelwarehouse::Entity")]
    WarehouseChannelwarehouse,
    #[sea_orm(has_many = "super::warehouse_stock::Entity")]
    WarehouseStock,
    #[sea_orm(has_many = "super::warehouse_warehouse_shipping_zones::Entity")]
    WarehouseWarehouseShippingZones,
}

impl Related<super::account_address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountAddress.def()
    }
}

impl Related<super::checkout_checkout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckout.def()
    }
}

impl Related<super::order_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderOrder.def()
    }
}

impl Related<super::warehouse_channelwarehouse::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseChannelwarehouse.def()
    }
}

impl Related<super::warehouse_stock::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseStock.def()
    }
}

impl Related<super::warehouse_warehouse_shipping_zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseWarehouseShippingZones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
