//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "warehouse_channelwarehouse")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub warehouse_id: Uuid,
    pub channel_id: i32,
    pub sort_order: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelChannel,
    #[sea_orm(
        belongs_to = "super::warehouse_warehouse::Entity",
        from = "Column::WarehouseId",
        to = "super::warehouse_warehouse::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WarehouseWarehouse,
}

impl Related<super::channel_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelChannel.def()
    }
}

impl Related<super::warehouse_warehouse::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseWarehouse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
