//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "warehouse_reservation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub quantity_reserved: i32,
    pub reserved_until: DateTimeWithTimeZone,
    pub stock_id: i32,
    pub checkout_line_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::checkout_checkoutline::Entity",
        from = "Column::CheckoutLineId",
        to = "super::checkout_checkoutline::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CheckoutCheckoutline,
    #[sea_orm(
        belongs_to = "super::warehouse_stock::Entity",
        from = "Column::StockId",
        to = "super::warehouse_stock::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WarehouseStock,
}

impl Related<super::checkout_checkoutline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutCheckoutline.def()
    }
}

impl Related<super::warehouse_stock::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WarehouseStock.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
