//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webhook_webhook")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub target_url: String,
    pub is_active: bool,
    pub secret_key: Option<String>,
    pub app_id: i32,
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub subscription_query: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_headers: Option<Json>,
    pub filterable_channel_slugs: Vec<String>,
    pub identifier: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_app::Entity",
        from = "Column::AppId",
        to = "super::app_app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppApp,
    #[sea_orm(has_many = "super::core_eventdelivery::Entity")]
    CoreEventdelivery,
    #[sea_orm(has_many = "super::webhook_webhookevent::Entity")]
    WebhookWebhookevent,
}

impl Related<super::app_app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppApp.def()
    }
}

impl Related<super::core_eventdelivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreEventdelivery.def()
    }
}

impl Related<super::webhook_webhookevent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookWebhookevent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
