[package]
name = "saleor-rustify-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
base64 = { workspace = true }
serde_json = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
pbkdf2 = { workspace = true }
bcrypt = { workspace = true }
jsonwebtoken = { workspace = true }
sha1 = { workspace = true }
digest = { workspace = true }
rsa = { workspace = true }
saleor-rustify-proto = { path = "../proto" }
rand = { workspace = true }
rust_decimal_macros = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
